'use strict';
const $=id=>document.getElementById(id), S={chats:[],settings:{},categories:[],selected:null,type:'all',details:false,messages:[],older:0,newer:0,loading:false,generation:0,selectionRequest:0,searchGen:0,scan:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=(tag,cls,text)=>{let n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
async function api(path,data,options={}){let controller=new AbortController(),parent=options.controller?.signal,abort=()=>controller.abort(),timeout=path==='/api/pick-folder'?180000:/^\/api\/(state|catalog)/.test(path)?5000:path.startsWith('/api/messages')?60000:15000;parent?.addEventListener('abort',abort,{once:true});if(parent?.aborted)abort();let stage='server response',timer=setTimeout(abort,timeout);try{let r=await fetch(path,{headers:data?{'Content-Type':'application/json'}:{},method:data?'POST':'GET',body:data?JSON.stringify(data):undefined,signal:controller.signal});stage='response body';if(path.startsWith('/api/messages')){clearTimeout(timer);timer=setTimeout(abort,5000);}let x=await r.json();if(!r.ok||x.error)throw Error(x.error||r.statusText);return x;}catch(e){if(e.name==='AbortError')throw Error(parent?.aborted?'A different conversation was opened.':'Timed out receiving '+path.split('?')[0]+' '+stage+'. Folder controls remain available.');throw e;}finally{clearTimeout(timer);parent?.removeEventListener('abort',abort);}}
async function fetchPage(extra,controller){try{return await api(pageURL({bytes:S.pageBytes||32768,...extra}),undefined,{controller});}catch(e){if(controller?.signal.aborted||!e.message.includes('response body'))throw e;S.pageBytes=8192;return api(pageURL({...extra,limit:extra.around!==undefined?20:Math.min(2,+extra.limit||5),bytes:8192}),undefined,{controller});}}
function loadScript(path,timeout=12000){return new Promise((resolve,reject)=>{let script=document.createElement('script');script.src=path;let timer=setTimeout(()=>{script.remove();reject(Error('Reader asset could not load: '+path));},timeout);script.onload=()=>{clearTimeout(timer);resolve();};script.onerror=()=>{clearTimeout(timer);reject(Error('Reader asset could not load: '+path));};document.head.append(script);});}
async function loadRenderer(name){let text='',offset=0,deadline=Date.now()+9000;
 while(true){let part,last;for(let attempt=0;attempt<3;attempt++){const remaining=deadline-Date.now();if(remaining<=0)throw Error('Formula renderer download timed out');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.min(1800,remaining));try{const response=await fetch('/api/renderer?'+new URLSearchParams({name,offset}),{signal:controller.signal});if(!response.ok)throw Error('Formula renderer returned '+response.status);part=await response.json();break;}catch(error){last=error;}finally{clearTimeout(timer);}await new Promise(resolve=>setTimeout(resolve,100*(attempt+1)));}if(!part)throw last;if(!part.done&&part.next<=offset)throw Error('Formula renderer download did not advance');text+=part.text;offset=part.next;if(part.done)break;}
 let url=URL.createObjectURL(new Blob([text],{type:'text/javascript'}));try{await loadScript(url,3000);}finally{URL.revokeObjectURL(url);}}
let readers=null,mathRetryCount=0,mathRetryTimer=null;
function loadReaders(){if(readers&&!readers.failed)return readers;clearTimeout(mathRetryTimer);if(!document.querySelector('link[data-math-style]')){let style=document.createElement('link');style.rel='stylesheet';style.href='vendor/katex/katex.min.css?v=1.0.11';style.dataset.mathStyle='1';document.head.append(style);}let current={markdown:Promise.resolve(),math:loadScript('vendor/katex/katex.min.js?v=1.0.11',5000).catch(()=>loadRenderer('katex')),failed:false};readers=current;current.math.then(()=>{mathRetryCount=0;Reader.typeset(document);}).catch(()=>{current.failed=true;document.querySelectorAll('.math-retry').forEach(b=>{b.textContent='Retry formula';b.disabled=false;});if(mathRetryCount<2)mathRetryTimer=setTimeout(()=>{mathRetryCount++;loadReaders();},500*(mathRetryCount+1));});return current;}

function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,5000);}
function safeRun(f){return (...args)=>Promise.resolve().then(()=>f(...args)).catch(e=>toast(e.message));}
function modal(id){$(id).showModal();}
function safeOnline(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
function displayTitle(c){return c.alias||c.title||'Untitled conversation';}
function kind(c){const value=String(S.settings.kindOverrides?.[c.id]||c.kind||'').toLowerCase();return /\bcodex\b/.test(value)?'codex':/\bwork\b|\bworkmode\b/.test(value)?'work':'chat';}
function saveSetting(key,val){S.settings[key]=val;return api('/api/settings',{[key]:val});}
function applyAppearance(){let s=S.settings;let theme=s.theme||'dark';let palettes={dark:['#212121','#171717','#ececec','#9b9b9b','#2f2f2f','#303030','#ffffff12'],black:['#000000','#080808','#ececec','#929292','#191919','#222222','#ffffff18'],light:['#ffffff','#f9f9f9','#222222','#727272','#f0f0f0','#e9e9e9','#00000012']};let p=palettes[theme]||[s.bg||'#212121',s.side||'#171717',s.text||'#ececec','#999999','#ffffff12','#ffffff18','#88888830'];let keys=['bg','side','text','muted','panel','hover','border'];keys.forEach((k,i)=>document.documentElement.style.setProperty('--'+k,p[i]));document.documentElement.style.setProperty('color-scheme',theme==='light'?'light':'dark');document.documentElement.style.setProperty('--accent',s.accent||'#10a37f');document.documentElement.style.setProperty('--font',(s.fontSize||16)+'px');document.documentElement.style.setProperty('--width',(s.width||800)+'px');}
function applySettings(){applyAppearance();$('sort').value=S.settings.sort||'newest';$('group').value=S.settings.group||'categories';$('show-projects').checked=S.settings.showProjects!==false;S.categories=S.settings.categories||[];S.type=S.settings.type||'all';document.querySelectorAll('[data-type]').forEach(n=>n.classList.toggle('active',n.dataset.type===S.type));if(S.settings.collapsed||innerWidth<600)document.body.classList.add('collapsed');}
function sortedChats(chats){let sort=$('sort').value;return chats.slice().sort((a,b)=>b.pinned-a.pinned||(sort==='manual'?a.position-b.position:sort==='oldest'?a.created-b.created:sort==='title'?displayTitle(a).localeCompare(displayTitle(b)):sort==='updated'?b.updated-a.updated:b.created-a.created));}
let sidebarGeneration=0;
function renderSidebar(){let box=$('chat-list'),savedScroll=box.scrollTop,gen=++sidebarGeneration;S.sidebarRendering=true;box.replaceChildren();let list=sortedChats(S.chats.filter(c=>(S.type==='all'||kind(c)===S.type)&&($('show-projects').checked||!c.project)));let groups=new Map(),mode=$('group').value;
 if(mode==='categories')S.categories.forEach(c=>groups.set('category:'+c,[]));
 for(let c of list){let key=c.pinned?'pinned':mode==='folders'?'folder:'+(c.folder||'Root'):mode==='types'?'type:'+kind(c):mode==='none'?'all':c.category?'category:'+c.category:c.project?'project:'+c.project:'uncategorized';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(c);}
 if(groups.has('pinned'))groups=new Map([['pinned',groups.get('pinned')],...[...groups].filter(([k])=>k!=='pinned')]);
 const closed=S.settings.closedGroups||[];
 function* nodes(){
 for(let [key,chats] of groups){let name=key==='pinned'?'Pinned':key==='uncategorized'?'Conversations':key==='all'?'All conversations':key.substring(key.indexOf(':')+1);let head=el('div','group-heading');head.dataset.group=key;
 let button=el('button','group-name',(closed.includes(key)?'▸ ':'▾ ')+(key.startsWith('project:')?'▱ ':'')+name);button.title=name;button.onclick=safeRun(async()=>{let next=closed.includes(key)?closed.filter(k=>k!==key):[...closed,key];await saveSetting('closedGroups',next);renderSidebar();});head.append(button,el('span','count',chats.length));
 if(key.startsWith('category:')){let rename=el('button','manage-group','⋯');rename.title='Rename or remove category';rename.onclick=safeRun(()=>manageCategory(name));head.append(rename);head.ondragover=e=>{e.preventDefault();head.classList.add('drop-target');};head.ondragleave=()=>head.classList.remove('drop-target');head.ondrop=safeRun(async e=>{e.preventDefault();head.classList.remove('drop-target');let cid=e.dataTransfer.getData('text/plain');if(!S.chats.some(c=>c.id===cid))return;await organize(cid,{category:name});renderSidebar();});}
 yield head;if(closed.includes(key))continue;
 for(let c of chats){let row=el('div','chat-row'+(c.id===S.selected?.id?' selected':''));row.draggable=true;row.dataset.id=c.id;let b=el('button','', (c.pinned?'☆ ':'')+displayTitle(c));b.title=displayTitle(c)+'\n'+c.id+'\n'+(S.settings.kindOverrides?.[c.id]?'Manual type: '+kind(c):c.kind_evidence||'Type: '+kind(c));b.onclick=safeRun(()=>openChat(c.id));let more=el('button','row-menu','⋯');more.title='Organize conversation';more.onclick=()=>manageChat(c);row.append(b,more);row.ondragstart=e=>{e.dataTransfer.setData('text/plain',c.id);row.classList.add('dragging');};row.ondragend=()=>row.classList.remove('dragging');row.ondragover=e=>{e.preventDefault();row.classList.add('drop-target');};row.ondragleave=()=>row.classList.remove('drop-target');row.ondrop=safeRun(async e=>{e.preventDefault();row.classList.remove('drop-target');let id=e.dataTransfer.getData('text/plain');if(id===c.id||!S.chats.some(x=>x.id===id))return;let reordered=chats.filter(x=>x.id!==id),idx=reordered.findIndex(x=>x.id===c.id),moving=S.chats.find(x=>x.id===id);reordered.splice(idx,0,moving);await organize(id,{category:c.category||''});for(let i=0;i<reordered.length;i++)await organize(reordered[i].id,{position:i*10});await saveSetting('sort','manual');$('sort').value='manual';renderSidebar();});yield row;}}
 }
 const iterator=nodes();function batch(){if(gen!==sidebarGeneration)return;let fragment=document.createDocumentFragment(),rows=0,next;while(rows<5&&!(next=iterator.next()).done){fragment.append(next.value);if(next.value.classList.contains('chat-row'))rows++;}box.append(fragment);box.scrollTop=savedScroll;if(!next?.done)setTimeout(batch,S.loading?16:8);else{S.sidebarRendering=false;if(S.sidebarPending){S.sidebarPending=false;renderSidebar();}}}batch();
 if(!list.length){const label={chat:'Chat',work:'Work',codex:'Codex'}[S.type];let message=S.chats.length?(label?'No '+label+' conversations detected in this view.':'No conversations match these filters.'):'Reading saved chat titles…';if(S.chats.length&&(S.catalogBusy||S.scan?.scanning))message+=' More saved type metadata is still loading.';if(!$('show-projects').checked)message+=' Projects are hidden.';box.append(el('div','empty-list',message));}
 $('archive-count').textContent=Math.max(S.chats.length,S.coverage?.available||0).toLocaleString()+' available chats'+(S.coverage?.expected?' / '+S.coverage.expected.toLocaleString()+' listed in export':'')+(S.catalogBusy?' · '+S.chats.length.toLocaleString()+' titles loaded':'');box.scrollTop=savedScroll;}
async function organize(id,values){await api('/api/organize',{id,...values});Object.assign(S.chats.find(c=>c.id===id)||{},values);}
async function manageCategory(name){let answer=prompt('Rename category, or leave empty to remove it. Chats will stay in your archive.',name);if(answer===null||answer===name)return;answer=answer.trim();if(answer&&S.categories.includes(answer))throw Error('A category with that name already exists.');for(let c of S.chats.filter(c=>c.category===name))await organize(c.id,{category:answer});await saveSetting('categories',answer?S.categories.map(c=>c===name?answer:c):S.categories.filter(c=>c!==name));S.categories=S.settings.categories;renderSidebar();}
function openPendingChat(){if(S.pendingChat&&!S.selected&&S.chats.some(c=>c.id===S.pendingChat.id)){let pending=S.pendingChat;S.pendingChat=null;openChat(pending.id,pending.seq,false,pending.leaf).catch(e=>toast(e.message));}}
function mergeCatalog(rows){let byId=new Map(S.chats.map(c=>[c.id,c]));for(let c of rows)byId.set(c.id,c);S.chats=[...byId.values()];let selected=S.chats.find(c=>c.id===S.selected?.id);if(selected){S.selected=selected;$('kind-pill').textContent=kind(selected)+(selected.project?' · '+selected.project:'');}openPendingChat();if(S.sidebarRendering)S.sidebarPending=true;else renderSidebar();}
async function hydrateCatalog(catalog){
 if(!catalog||catalog.nextOffset===null)return;
 if(S.catalogBusy){S.catalogQueued=catalog;return;}
 S.catalogBusy=true;let current=catalog,limit=25;
 try{while(current){let offset=current.nextOffset;
  while(offset!==null){
   // One bounded request at a time. Message requests use a separate connection.
   let page;try{page=await api('/api/catalog?'+new URLSearchParams({offset,limit,priority:current.priority||''}));}
   catch(e){if(limit>5){limit=5;continue;}throw e;}
   mergeCatalog(page.chats);offset=page.nextOffset;await new Promise(r=>setTimeout(r,S.loading?30:8));
  }
  current=S.catalogQueued;S.catalogQueued=null;
 }}catch(e){S.catalogRetry=current;$('startup-note').hidden=false;$('startup-note').textContent='Loaded '+S.chats.length+' titles; remaining titles will retry. '+e.message;}
 finally{S.catalogBusy=false;if(S.sidebarRendering)S.sidebarPending=true;else renderSidebar();}
}
async function refresh(initial=false){if(S.refreshing)return null;S.refreshing=true;try{
 const query=new URLSearchParams();if(!initial&&S.revision!==undefined)query.set('since',S.revision);let priority=new URLSearchParams(location.hash.slice(1)).get('chat')||S.pendingChat?.id||S.selected?.id||S.settings.lastChat;if(priority)query.set('priority',priority);
 const x=await api('/api/state'+(query.size?'?'+query:''));
 $('startup-note').hidden=true;
 const changed=Array.isArray(x.chats);if(changed)S.revision=x.revision;S.scan=x.scan;S.coverage=x.coverage;
 if(initial){S.settings={...x.settings,...S.settings};applySettings();S.initialized=true;}
 S.settings.scan_start=x.settings.scan_start||S.settings.scan_start;S.settings.scan_up=x.settings.scan_up??S.settings.scan_up;S.settings.scanPaused=!!x.settings.scanPaused;
 $('status').textContent=x.scan.phase+(x.scan.scanning?' · '+(x.coverage?.indexed||0)+' indexed, still working':'');$('welcome-status').textContent=x.scan.phase;
 $('scan-status').textContent=x.scan.phase;
 $('scan-progress').textContent=(x.scan.files||0).toLocaleString()+' files found · '+(x.scan.processed||0).toLocaleString()+' checked · '+(x.scan.indexed||0).toLocaleString()+' chats updated · '+(x.scan.cached||0).toLocaleString()+' unchanged';
 $('scan-location').textContent='Scan boundary: '+(x.scan.roots?.join(', ')||'Not selected')+'\nCurrent folder: '+(x.scan.current_folder||'—')+(x.scan.current_file?'\nCurrent file: '+x.scan.current_file:'');
 let notes=[...x.scan.errors];if(x.coverage?.expected){$('scan-progress').textContent+='\n'+x.coverage.indexed+' indexed · '+x.coverage.available+' available · '+x.coverage.expected+' listed in manifest';if(x.coverage.missing)notes.push(x.coverage.missing+' manifest entries have no saved MD/JSON file found at their recorded path in this boundary. Discovery may still find them elsewhere.',...x.coverage.examples.map(c=>c.title+' · '+c.id));}$('scan-errors').querySelector('pre').textContent=notes.join('\n');$('scan-errors').hidden=!notes.length;
 $('scan-toggle').textContent=x.scan.scanning?'Pause discovery':'Resume / rescan';$('stop-scan').disabled=!x.scan.scanning;
 const sm=x.semantic;$('semantic-status').textContent=sm.building?(sm.phase||'Building index')+(sm.count?' · '+sm.count.toLocaleString()+' chunks':''):sm.ready?'Ready · '+sm.count.toLocaleString()+' indexed chunks':sm.error||'Optional model is not indexed yet.';$('build-semantic').disabled=sm.building;
 if(initial){if(!$('folder-path').value)$('folder-path').value=S.settings.scan_start||'';$('scan-up').value=S.settings.scan_up??2;
 let hash=new URLSearchParams(location.hash.slice(1)),cid=hash.get('chat')||S.settings.lastChat;
 if(cid)S.pendingChat={id:cid,seq:hash.has('message')?+hash.get('message'):null,leaf:hash.get('leaf')};}
 if(changed){if(x.catalog)mergeCatalog(x.chats);else{S.chats=x.chats;mergeCatalog([]);}hydrateCatalog(x.catalog);}
 else if(S.catalogRetry&&!S.catalogBusy){let retry=S.catalogRetry;S.catalogRetry=null;hydrateCatalog(retry);}
 openPendingChat();
 return x;
 }finally{S.refreshing=false;}}

function markdown(text,cid,extras,key,m){return Reader.create(m||{text,extras},cid,key||cid);}
function renderMessage(m){const cid=S.selected.id,leaf=S.leaf;let node=el('article','message '+(m.role==='user'?'user':m.visible?'assistant':'details'));node.dataset.seq=m.seq;if(m.extras?.presentation?.kind==='output')node.classList.add('execution-message');let label=el('div','message-label');if(m.role!=='user')label.append(el('span','',m.role==='assistant'?(m.channel&&m.channel!=='final'?'ChatGPT · '+m.channel:'ChatGPT'):m.role+' · '+(m.channel||'output')));if(S.settings.showDates&&m.time)label.append(el('span','message-time',new Date(m.time*1000).toLocaleString()));if(label.childNodes.length)node.append(label);
 let body=el('div','message-body');if(m.role==='user'){body.textContent=m.text;if(m.text_complete===false){let more=el('button','format-status','Load complete message');more.onclick=safeRun(async()=>{const text=await Reader.fullText(m,cid,leaf);body.textContent=text;});body.append(more);}}else body.append(markdown(m.text,S.selected.id,m.extras,[S.selected.id,S.leaf||'',m.seq].join('|'),m));let fold=el('details','message-fold'),summary=el('summary','message-summary');if(!label.childNodes.length)label.append(el('span','',m.role==='user'?'You':m.role));summary.append(label);fold.append(summary,body);Reader.foldState(fold,[S.selected.id,S.leaf||'',m.seq,'message'].join('|'),m.role==='user'||!!m.visible);node.append(fold);let tools=el('div','message-tools'),copy=el('button','','⧉'),link=el('button','','↗');copy.title='Copy message';copy.onclick=safeRun(async()=>{await navigator.clipboard.writeText(await Reader.fullText(m,cid,leaf));toast('Message copied');});link.title='Copy local message link';link.onclick=safeRun(async()=>{await navigator.clipboard.writeText(location.origin+'/#chat='+encodeURIComponent(S.selected.id)+'&message='+m.seq+(S.leaf?'&leaf='+encodeURIComponent(S.leaf):''));toast('Local message link copied; open the viewer first when using it.');});tools.append(copy,link);let ex=m.extras||{};if(ex.versions?.length>1){let vc=el('span','version-controls'),i=ex.versions.indexOf(ex.node_id);let prev=el('button','','‹'),next=el('button','','›');prev.title='Previous version';next.title='Next version';prev.disabled=i<=0;next.disabled=i>=ex.versions.length-1;prev.onclick=safeRun(()=>switchVersion(ex.versions[i-1]));next.onclick=safeRun(()=>switchVersion(ex.versions[i+1]));vc.append(prev,el('span','',(i+1)+'/'+ex.versions.length),next);tools.append(vc);}let receipt=ex.receipt;if(m.role==='assistant'&&receipt?.served){let label=receipt.served+(receipt.rerouted?' · rerouted from '+receipt.picked:'')+(receipt.effort?' · effort '+receipt.effort:'');let badge=el('button','model-badge'+(receipt.rerouted?' rerouted':''),label);badge.title=JSON.stringify(receipt.raw,null,2)+'\nClick to copy saved metadata';badge.onclick=safeRun(async()=>{await navigator.clipboard.writeText(JSON.stringify(receipt.raw,null,2));toast('Saved model metadata copied');});tools.append(badge);}node.append(tools);
return node;}
function renderMessages(){Reader.closeTable();Reader.release([...$('messages').children]);let fragment=document.createDocumentFragment();for(let m of S.messages)fragment.append(renderMessage(m));$('messages').replaceChildren(fragment);updatePaging();}
function updatePaging(){let total=S.total||0;$('load-older').hidden=!S.older;$('load-info').textContent=S.older?S.older.toLocaleString()+' older messages':'Start of saved conversation';$('bottom-loader').hidden=!S.newer;$('end-card').hidden=!!S.newer;$('message-stat').textContent=S.messages.length+' shown · '+total.toLocaleString()+' messages';$('end-meta').textContent=(S.selected?.created?new Date(S.selected.created*1000).toLocaleDateString()+' · ':'')+total.toLocaleString()+' visible messages · '+kind(S.selected||{});
 let u=safeOnline(S.selected?.url);$('continue').hidden=!u;if(u)$('continue').href=u;$('details-toggle').textContent='Tool details '+(S.details?'on':'off');$('pin-chat').textContent=S.selected?.pinned?'★':'☆';}
function pageURL(extra={}){let p=new URLSearchParams({id:S.selected.id,limit:S.settings.pageSize||100,details:S.details?'1':'0',...(S.leaf?{leaf:S.leaf}:{}),...extra});return '/api/messages?'+p;}
const warmChats=new Map();
function rememberChat(){if(!S.selected||!S.messages.length||S.loading)return;let key=S.renderKey||cacheKey(S.selected.id,S.leaf);warmChats.delete(key);warmChats.set(key,{messages:S.messages.slice(),nodes:[...$('messages').children],older:S.older,newer:S.newer,total:S.total,top:$('scroller').scrollTop,fingerprint:S.selected.fingerprint});while(warmChats.size>5){const oldest=warmChats.keys().next().value;Reader.release(warmChats.get(oldest).nodes);warmChats.delete(oldest);};}
function cacheKey(id,leaf){return [id,leaf||'',S.details,S.settings.pageSize||100].join('|');}
const frame=()=>new Promise(r=>setTimeout(r,0));
async function upgradeReader(){let gen=S.generation;S.loading=true;try{await renderProgressively(gen,true);}finally{if(gen===S.generation)S.loading=false;}}
async function renderProgressively(gen,preserve=false,target=null){
 const box=$('messages'),scroller=$('scroller'),top=scroller.scrollTop,oldHeight=scroller.scrollHeight;
 const data=S.messages.slice(),tail=data.slice(-20);box.replaceChildren();
 for(let i=0;i<tail.length;i+=5){if(gen!==S.generation)return;box.append(...tail.slice(i,i+5).map(renderMessage));await frame();}
 if(!preserve&&target===null)scroller.scrollTop=scroller.scrollHeight;
 for(let end=data.length-20;end>0;end-=5){if(gen!==S.generation)return;let height=scroller.scrollHeight;box.prepend(...data.slice(Math.max(0,end-5),end).map(renderMessage));scroller.scrollTop+=scroller.scrollHeight-height;await frame();}
 if(gen!==S.generation)return;updatePaging();if(preserve)scroller.scrollTop=top+(scroller.scrollHeight-oldHeight);else if(target!==null)focusMessage(target);else scroller.scrollTop=scroller.scrollHeight;
}
async function openChat(id,seq=null,latest=false,leaf=null){
 Reader.closeTable();Reader.cancel();
 let request=++S.selectionRequest;S.pendingChat=null;let c=S.chats.find(x=>x.id===id);if(!c){let page=await api('/api/catalog?'+new URLSearchParams({priority:id,limit:1}));if(request!==S.selectionRequest)return;c=page.chats.find(x=>x.id===id);if(!c)throw Error('This conversation has not been discovered yet.');mergeCatalog([c]);}
 rememberChat();S.activeController?.abort();S.activeController=new AbortController();let controller=S.activeController;
 let gen=++S.generation;S.selected=c;S.leaf=leaf;S.renderKey=cacheKey(id,leaf);S.pageBytes=32768;S.loading=true;S.messages=[];
 $('messages').replaceChildren();$('message-stat').textContent='Opening selected conversation…';$('welcome').hidden=true;$('conversation').hidden=false;$('end-card').hidden=true;$('bottom-loader').hidden=true;
 $('chat-title').textContent=displayTitle(c);$('kind-pill').textContent=kind(c)+(c.project?' · '+c.project:'');$('kind-pill').hidden=false;
 document.querySelectorAll('.chat-row').forEach(row=>row.classList.toggle('selected',row.dataset.id===id));
 $('load-older').hidden=true;$('load-info').textContent='Opening selected conversation…';if(innerWidth<600)document.body.classList.add('collapsed');
 let position=S.settings.rememberPosition&&!latest?S.settings.positions?.[id]:null,target=seq!==null?seq:position??null;
 loadReaders();
 try{
  let cached=seq===null&&!latest?warmChats.get(cacheKey(id,leaf)):null;
  if(cached&&(!cached.fingerprint||!c.fingerprint||cached.fingerprint===c.fingerprint)){
   Object.assign(S,{messages:cached.messages,older:cached.older,newer:cached.newer,total:cached.total});$('messages').replaceChildren(...cached.nodes);Reader.resume(cached.nodes);updatePaging();$('scroller').scrollTop=cached.top;
  }else{
   let page=await fetchPage(target!==null?{around:target,limit:20}:{limit:5},controller);if(gen!==S.generation)return;
   Object.assign(S,{messages:page.messages,older:page.older,newer:page.newer,total:page.total});await renderProgressively(gen,false,target);if(gen!==S.generation)return;
  }
  location.hash='chat='+encodeURIComponent(id)+(seq!==null?'&message='+seq:'')+(S.leaf?'&leaf='+encodeURIComponent(S.leaf):'');saveSetting('lastChat',id).catch(()=>{});
 }catch(e){if(gen!==S.generation)return;$('load-info').textContent='Could not open this chat: '+e.message;$('load-older').hidden=false;$('load-older').textContent='Retry opening chat';$('load-older').onclick=safeRun(()=>openChat(id,seq,latest,leaf));throw e;}
 finally{if(gen===S.generation){S.loading=false;if(S.messages.length){$('load-older').textContent='Load older messages';$('load-older').onclick=safeRun(()=>loadPage('older'));Reader.typeset(document);primeHistory(gen).catch(e=>{if(gen===S.generation)toast(e.message);});}}}
}
function focusMessage(seq){let n=$('messages').querySelector('[data-seq="'+Number(seq)+'"]');if(n){Reader.prioritize(n);n.scrollIntoView({block:'start'});n.classList.add('focused');setTimeout(()=>n.classList.remove('focused'),2500);}}
async function primeHistory(gen){if(S.priming===gen)return;S.priming=gen;try{while(gen===S.generation&&S.messages.length<(S.settings.pageSize||100)&&S.older){if(S.loading){await new Promise(r=>setTimeout(r,25));continue;}await loadPage('older',Math.min(10,(S.settings.pageSize||100)-S.messages.length));await new Promise(r=>setTimeout(r,25));}}finally{if(S.priming===gen)S.priming=null;}}
async function loadPage(direction,limit=20){if(S.loading||!S.selected||!(direction==='older'?S.older:S.newer))return;S.loading=true;let gen=S.generation;let scroller=$('scroller'),beforeHeight=scroller.scrollHeight,oldTop=scroller.scrollTop,first=$('messages').firstElementChild;
 try{let extra=direction==='older'?{before:S.messages[0].seq,limit}:{after:S.messages.at(-1).seq,limit};let p=await fetchPage(extra,S.activeController);if(gen!==S.generation)return;let nodes=[];for(let i=0;i<p.messages.length;i+=5){nodes.push(...p.messages.slice(i,i+5).map(renderMessage));await frame();if(gen!==S.generation)return;}if(direction==='older'){S.messages=[...p.messages,...S.messages];$('messages').prepend(...nodes);S.older=p.older;scroller.scrollTop=oldTop+(scroller.scrollHeight-beforeHeight);}else{S.messages.push(...p.messages);$('messages').append(...nodes);S.newer=p.newer;}
 // Keep at most 300 messages in the DOM and load either direction again as needed.
 if(S.messages.length>300){let cut=S.messages.length-300;if(direction==='older'){let removed=S.messages.splice(-cut);removed.forEach(m=>$('messages').querySelector('[data-seq="'+m.seq+'"]').remove());S.newer+=removed.length;}else{let h=scroller.scrollHeight;let removed=S.messages.splice(0,cut);removed.forEach(m=>$('messages').querySelector('[data-seq="'+m.seq+'"]').remove());S.older+=removed.length;scroller.scrollTop=Math.max(0,scroller.scrollTop-(h-scroller.scrollHeight));}}
 updatePaging();}finally{if(gen===S.generation)S.loading=false;}}
let scrollTimer;function onScroll(){if(!S.selected||S.loading)return;let sc=$('scroller');if(sc.scrollTop<220&&S.older)loadPage('older').catch(e=>toast(e.message));else if(sc.scrollHeight-sc.scrollTop-sc.clientHeight<260&&S.newer)loadPage('newer').catch(e=>toast(e.message));clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{if(!S.settings.rememberPosition)return;let rect=sc.getBoundingClientRect();let seen=[...$('messages').children].find(n=>n.getBoundingClientRect().bottom>rect.top+30);if(seen){let positions={...(S.settings.positions||{}),[S.selected.id]:+seen.dataset.seq};saveSetting('positions',positions).catch(e=>toast(e.message));}},600);}
async function search(){let q=$('search-query').value.trim(),gen=++S.searchGen;let box=$('search-results');if(!q){box.replaceChildren();$('search-meta').textContent='Search all saved messages. Select a match to jump to it.';return;}$('search-meta').textContent='Searching…';let start=performance.now(),r=await api('/api/search?'+new URLSearchParams({q,mode:$('search-mode').value}));if(gen!==S.searchGen)return;box.replaceChildren();$('search-meta').textContent=r.notice||r.results.length+' matches · '+r.mode+' · '+Math.round(performance.now()-start)+' ms';let groups=new Map();for(let hit of r.results){if(!groups.has(hit.cid))groups.set(hit.cid,[]);groups.get(hit.cid).push(hit);}for(let [cid,hits] of groups){for(let hit of hits.slice(0,3)){let b=el('button','search-result'),c=S.chats.find(x=>x.id===cid);b.append(el('strong','',displayTitle(c||hit)),...(hit.match?[el('small','search-match',' · '+hit.match)]:[]),el('small','', ' · '+(c?kind(c):'chat')+(c?.project?' · '+c.project:'')),el('p','',hit.snippet));b.onclick=safeRun(async()=>{$('search-dialog').close();await openChat(cid,hit.seq>=0?Number(hit.seq):null);});box.append(b);}}if(!r.results.length)box.append(el('p','muted','No matching saved messages. Try fewer words or Hybrid semantic after setting up the local model.'));}
let searchTimer;function scheduleSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>search().catch(e=>toast(e.message)),180);}
function openSettings(){let s=S.settings;$('theme').value=s.theme||'dark';$('accent').value=s.accent||'#10a37f';$('bg-color').value=s.bg||'#212121';$('side-color').value=s.side||'#171717';$('text-color').value=s.text||'#ececec';$('font-size').value=s.fontSize||16;$('reading-width').value=s.width||800;$('page-size').value=s.pageSize||100;$('font-value').textContent=$('font-size').value+' px';$('width-value').textContent=$('reading-width').value+' px';$('remember-position').checked=!!s.rememberPosition;$('auto-refresh').checked=s.autoRefresh!==false;$('show-dates').checked=!!s.showDates;modal('settings-dialog');}
function appearanceInputs(){Object.assign(S.settings,{theme:$('theme').value,accent:$('accent').value,bg:$('bg-color').value,side:$('side-color').value,text:$('text-color').value,fontSize:+$('font-size').value,width:+$('reading-width').value});$('font-value').textContent=$('font-size').value+' px';$('width-value').textContent=$('reading-width').value+' px';applyAppearance();}
async function saveSettings(){appearanceInputs();Object.assign(S.settings,{pageSize:+$('page-size').value,rememberPosition:$('remember-position').checked,autoRefresh:$('auto-refresh').checked,showDates:$('show-dates').checked});await api('/api/settings',S.settings);$('settings-dialog').close();if(S.selected)renderMessages();}
function manageChat(c=S.selected){if(!c)return;S.managing=c;$('alias').value=displayTitle(c);$('chat-category').replaceChildren();for(let category of ['',...S.categories]){let o=el('option','',category||'Uncategorized');o.value=category;$('chat-category').append(o);}$('chat-category').value=c.category;$('chat-kind').value=kind(c);$('source-path').textContent='Source: '+c.path;modal('manage-dialog');}
async function pickFolder(){let b=$('pick-folder');b.disabled=true;b.textContent='Opening folder dialog…';try{let p=await api('/api/pick-folder',{path:$('folder-path').value});if(p.path){$('folder-path').value=p.path;$('scan-up').value='0';}}finally{b.disabled=false;b.textContent='Browse…';}}
function downloadJson(name,data){let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=el('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function inChatSearch(){let q=$('inchat-query').value.trim();if(!q||!S.selected)return;let r=await api('/api/search?'+new URLSearchParams({q,mode:'keyword',id:S.selected.id}));let hit=r.results.find(x=>x.cid===S.selected.id&&x.seq>=0);if(hit)await openChat(hit.cid,+hit.seq);else toast('No match in the indexed selected branch.');}
async function switchVersion(target){if(!target||!S.selected)return;let id=S.selected.id;let v=await api('/api/version?'+new URLSearchParams({id,target}));await openChat(id,v.seq,false,v.leaf);toast('Saved message version opened; later messages follow that branch');}
async function showBranches(){if(!S.selected)return;let r=await api('/api/branches?'+new URLSearchParams({id:S.selected.id}));$('branch-list').replaceChildren();for(let branch of r.branches){let b=el('button','',(branch.selected?'Selected branch · ':'Alternate branch · ')+(branch.time?new Date(branch.time*1000).toLocaleDateString():'')+'\n'+branch.preview);b.onclick=safeRun(async()=>{let id=S.selected.id;$('branch-dialog').close();await openChat(id,null,true,branch.id);toast('Saved branch opened · reopen the sidebar chat to return to the original selection');});$('branch-list').append(b);}if(!r.branches.length)$('branch-list').append(el('p','muted','This source is Markdown or has no saved branch mapping.'));modal('branch-dialog');}

function events(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){let r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));$('collapse').onclick=safeRun(async()=>{document.body.classList.add('collapsed');await saveSetting('collapsed',true);});$('expand').onclick=safeRun(async()=>{document.body.classList.remove('collapsed');await saveSetting('collapsed',false);});$('home').onclick=()=>{rememberChat();S.activeController?.abort();S.generation++;S.selectionRequest++;S.loading=false;S.selected=null;$('welcome').hidden=false;$('conversation').hidden=true;$('chat-title').textContent='Your conversations';$('kind-pill').hidden=true;renderSidebar();};
 const searchOpen=()=>{modal('search-dialog');$('search-query').focus();};$('search-open').onclick=searchOpen;$('search-query').oninput=scheduleSearch;$('search-mode').onchange=scheduleSearch;
 for(let id of ['scan-open','welcome-folder'])$(id).onclick=()=>modal('folder-dialog');$('pick-folder').onclick=safeRun(pickFolder);$('rescan').onclick=safeRun(async()=>{let path=$('folder-path').value.trim();if(!path)throw Error('Choose or enter your export folder first.');await api('/api/scan',{path,up:+$('scan-up').value});S.settings.scanPaused=false;toast('Scanning your chosen folder; chats appear as they are indexed');await refresh();});
 $('stop-scan').onclick=safeRun(async()=>{await api('/api/stop-scan',{});S.settings.scanPaused=true;toast('Discovery stopped; cached chats remain readable');await refresh();});$('scan-toggle').onclick=safeRun(async()=>{if(S.scan?.scanning){await api('/api/stop-scan',{});S.settings.scanPaused=true;}else if(S.settings.scan_start){await api('/api/scan',{path:S.settings.scan_start,up:S.settings.scan_up??2});S.settings.scanPaused=false;}else modal('folder-dialog');await refresh();});
 $('sort').onchange=safeRun(async()=>{await saveSetting('sort',$('sort').value);renderSidebar();});$('group').onchange=safeRun(async()=>{await saveSetting('group',$('group').value);renderSidebar();});$('show-projects').onchange=safeRun(async()=>{await saveSetting('showProjects',$('show-projects').checked);renderSidebar();});document.querySelectorAll('[data-type]').forEach(b=>b.onclick=safeRun(async()=>{S.type=b.dataset.type;document.querySelectorAll('[data-type]').forEach(n=>n.classList.toggle('active',n===b));await saveSetting('type',S.type);renderSidebar();}));
 $('add-category').onclick=safeRun(async()=>{let name=prompt('Category name');if(!name?.trim())return;name=name.trim();if(S.categories.includes(name))throw Error('That category already exists.');await saveSetting('categories',[...S.categories,name]);S.categories=S.settings.categories;renderSidebar();});
 $('settings-open').onclick=openSettings;for(let id of ['theme','accent','bg-color','side-color','text-color','font-size','reading-width'])$(id).oninput=appearanceInputs;$('save-settings').onclick=safeRun(saveSettings);$('build-semantic').onclick=safeRun(async()=>{await api('/api/semantic',{});toast('Semantic setup/indexing started. You can keep reading; progress is in Settings.');});$('backup-settings').onclick=()=>downloadJson('offline-chat-viewer-settings.json',{schema:'offline-chat-viewer/v1',settings:S.settings,organization:S.chats.map(({id,category,pinned,position,alias})=>({id,category,pinned,position,alias}))});$('restore-settings').onclick=()=>$('settings-file').click();$('settings-file').onchange=safeRun(async()=>{let f=$('settings-file').files[0];if(!f)return;let d=JSON.parse(await f.text());if(d.schema!=='offline-chat-viewer/v1'||!d.settings||!Array.isArray(d.organization))throw Error('This is not a viewer settings backup.');for(let c of d.organization)await organize(c.id,{category:c.category||'',pinned:c.pinned?1:0,position:+c.position||0,alias:String(c.alias||'')});S.settings=d.settings;await api('/api/settings',S.settings);applySettings();renderSidebar();toast('Settings and organization restored');});
 $('shutdown').onclick=safeRun(async()=>{await api('/api/shutdown',{});$('settings-dialog').close();toast('Viewer stopped. Run START-VIEWER.bat to reopen it.');});$('chat-menu').onclick=()=>manageChat();$('pin-chat').onclick=safeRun(async()=>{if(!S.selected)return;await organize(S.selected.id,{pinned:S.selected.pinned?0:1});renderSidebar();updatePaging();});$('save-chat').onclick=safeRun(async()=>{let c=S.managing;await organize(c.id,{alias:$('alias').value.trim(),category:$('chat-category').value});await saveSetting('kindOverrides',{...(S.settings.kindOverrides||{}),[c.id]:$('chat-kind').value});$('manage-dialog').close();renderSidebar();if(c.id===S.selected?.id){$('chat-title').textContent=displayTitle(c);$('kind-pill').textContent=kind(c);}});
 $('scroller').addEventListener('scroll',onScroll,{passive:true});$('load-older').onclick=safeRun(()=>loadPage('older'));$('load-newer').onclick=safeRun(()=>loadPage('newer'));$('jump-bottom').onclick=safeRun(()=>S.selected&&openChat(S.selected.id,null,true,S.leaf));$('jump-first').onclick=safeRun(()=>S.selected&&openChat(S.selected.id,0,false,S.leaf));$('details-toggle').onclick=safeRun(async()=>{S.details=!S.details;if(S.selected)await openChat(S.selected.id,null,false,S.leaf);});$('branches').onclick=safeRun(showBranches);$('export-chat').onclick=()=>{if(S.selected){let a=el('a');a.href='/api/source?id='+encodeURIComponent(S.selected.id);a.download='';a.click();}};
 $('inchat-open').onclick=()=>{$('inchat-bar').hidden=!$('inchat-bar').hidden;if(!$('inchat-bar').hidden)$('inchat-query').focus();};$('inchat-close').onclick=()=>$('inchat-bar').hidden=true;$('inchat-search').onclick=safeRun(inChatSearch);$('inchat-query').onkeydown=e=>{if(e.key==='Enter')safeRun(inChatSearch)();};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('search-dialog').open)searchOpen();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'&&S.selected){e.preventDefault();$('inchat-bar').hidden=false;$('inchat-query').focus();}});
 document.body.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});document.body.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();toast('Choose the containing folder in Export folders so linked attachments and nearby exports can be discovered.');modal('folder-dialog');}});
}
function start(){events();Reader.bind();Reader.preload();$('reader-collapse').onclick=()=>Reader.setAll(false);$('reader-expand').onclick=()=>Reader.setAll(true);window.viewerAppStarted=true;$('startup-note').hidden=true;loadReaders();let wasScanning=false;
 async function poll(){let x=null;try{x=await refresh(!S.initialized);if(x){if(wasScanning&&!x.scan.scanning)toast(x.scan.phase);wasScanning=x.scan.scanning;}}catch(e){$('status').textContent='Waiting for index status · folder controls are available';$('startup-note').hidden=false;$('startup-note').textContent=e.message;}finally{setTimeout(poll,x?.cacheLoading?150:x?.scan?.scanning?800:2200);}}
 poll();setInterval(()=>{if(S.initialized&&S.settings.autoRefresh!==false&&!S.settings.scanPaused&&!S.scan?.scanning&&S.settings.scan_start)api('/api/scan',{path:S.settings.scan_start,up:S.settings.scan_up??2}).catch(()=>{});},60000);}
start();
