'use strict';
(()=>{
 let snapshot=null,open=false,timer=null,parents=[{id:'root',name:'My Drive'}],lastImported=0,submitting=false;
 const formatDate=value=>value?new Date(value*1000).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not yet';
 const percent=(done,total)=>total?Math.min(100,Math.round(done/total*100)):0;
 const formats=['markdown','json','images','files'];
 function fields(config){$('backup-follow-exporter').checked=config.follow_exporter!==false;for(const kind of formats)$('backup-include-'+kind).checked=(config.include_formats||formats).includes(kind);$('backup-source').value=config.source||'';$('backup-modes').value=config.modes||'both';$('backup-cadence').value=config.cadence||'daily';$('backup-idle').value=String(config.idle_minutes||10);$('backup-enabled').checked=!!config.enabled;$('backup-hours').value=$('backup-hours-number').value=String(config.interval_hours||24);hourLabel();for(const key of ['idle_required','ac_only','auto_upload','cleanup_extras'])$('backup-'+key.replaceAll('_','-')).checked=config[key]!==false;$('backup-follow-loader').checked=config.source_mode==='loader';$('backup-up').value=String(config.up||0);$('backup-route').value=config.route||'desktop';$('backup-local-folder').value=config.local_folder||'';$('backup-sync-folder').value=config.sync_folder||'';routeControls();sourceControls();}
 function render(data){snapshot=data;const config=data.config,connection=data.connection,p=data.progress||{},active=!!data.running||['Preparing backup','Finding linked attachments','Checking backup changes','Unpacking archive','Integrating conversations'].includes(p.phase)||/^Packaging|^Uploading|^Copying/.test(p.phase||'');
  if(open&&$('backup-follow-loader').checked&&config.source_mode==='loader'){$('backup-source').value=config.source||'';$('backup-up').value=String(config.up||0);}
  if(data.source_counts&&!active){$('backup-counts').textContent=contentSummary(data.source_counts);}
  $('backup-badge').textContent=active?'Working':p.error?'Attention':config.enabled?(config.interval_hours+'h'):'Off';$('backup-last').textContent=formatDate(data.last_success||data.last_local);$('backup-next').textContent=config.enabled?('Every '+config.interval_hours+' hours')+(config.idle_required?' · '+config.idle_minutes+' min idle':' · whenever due'):'Off';$('backup-attachments').textContent=data.missing_count===0?'All saved links included':data.missing_count?data.missing_count+' unavailable':'Checked during backup';
  $('drive-state').textContent=connection.connected?'Connected':connection.phase==='waiting'?'Waiting for Google':'Not connected';$('drive-state').classList.toggle('connected',connection.connected);$('drive-account').textContent=connection.connected?connection.account||'Google account connected':connection.error||'Choose the account in Google’s sign-in page.';$('drive-connect').hidden=connection.connected;$('drive-disconnect').hidden=!connection.connected;$('drive-connect').disabled=connection.phase==='waiting';$('drive-client-import').textContent=connection.client_ready?'Change connection JSON':'Import connection JSON';
  $('drive-selected').textContent=config.folder_name||'No Google Drive folder selected';$('backup-phase').textContent=p.phase||'Ready when you are';$('backup-percent').textContent=p.total?percent(p.done,p.total)+'%':'';$('backup-progress').value=percent(p.done,p.total);$('backup-current').textContent=p.current||'';$('backup-message').textContent=p.error||[p.message,p.warning].filter(Boolean).join(' · ');$('backup-run').disabled=submitting||(config.route==='desktop'?!config.sync_folder:!connection.connected||!config.folder_id);$('backup-preview').disabled=active;$('backup-saved-location').textContent='Local ZIP folder: '+config.local_folder;$('backup-local').disabled=submitting;$('backup-cancel').disabled=!active&&!data.queue?.pending&&!data.delivery_pending;
  $('backup-queue').textContent=[data.queue?.pending?data.queue.pending+' queued request'+(data.queue.pending===1?'':'s')+' · repeated requests are combined':'',data.delivery_pending?(data.retry_paused?'ZIP delivery paused · Retry resumes it':('Local ZIPs ready · delivery retries '+formatDate(data.retry_at))):''].filter(Boolean).join(' · ');$('backup-retry').hidden=!data.delivery_pending;$('backup-retry').disabled=active||submitting;
  $('drive-connect').disabled=!connection.client_ready||connection.phase==='waiting';$('drive-connect').title=connection.client_ready?'Sign in to Google in your browser':'Import the Desktop app connection JSON first';for(const id of ['drive-choose','drive-new-folder','drive-folder-use'])$(id).disabled=!connection.connected;
  const downloads=$('backup-downloads');downloads.replaceChildren();for(const mode of ['full','progress'])if(data.files?.[mode]?.sha256&&data.files[mode].exists){const bytes=data.files[mode].size||0,size=bytes>=1024**3?(bytes/1024**3).toFixed(2)+' GB':bytes>=1024**2?(bytes/1024**2).toFixed(1)+' MB':(bytes/1024).toFixed(1)+' KB';const link=el('a','',(mode==='full'?'Download full ZIP':'Download progress ZIP')+' · '+size);link.href='/api/backup/download?mode='+mode;link.download='Chat-Archive-'+mode+'.zip';link.title=mode==='full'?'Complete exported archive with saved attachments':'Changes since the previous successful backup; the first progress ZIP includes everything';downloads.append(link);if(config.route==='api'&&data.files[mode].webViewLink){const online=el('a','','Open '+mode+' on Drive');online.href=safeOnline(data.files[mode].webViewLink);online.target='_blank';online.rel='noopener noreferrer';downloads.append(online);}}
  $('backup-missing').hidden=!data.missing_count;$('backup-missing').querySelector('div').textContent=(data.missing||[]).map(r=>r.document+' → '+r.reference+' ('+r.reason+')').join('\n')+(data.missing_count>100?'\nMore details are included in the ZIP manifest.':'');
  if(data.last_import?.at>lastImported){lastImported=data.last_import.at;if(p.phase==='Import complete')safeRun(async()=>{await refresh();const state=await api('/api/state');S.settings=state.settings;applySettings();renderSidebar();})();}
  if(open&&$('backup-feedback').textContent.startsWith('Creating local ZIPs.')&&!active&&p.phase){feedback(p.error||p.message||p.phase,!!p.error);}
  draftReady(active);
 }
 function contentSummary(c){return c.markdown+' Markdown · '+c.json+' JSON · '+c.jsonl+' sessions · '+(c.images||0)+' images · '+(c.miscellaneous||0)+' other files · '+c.indexes+' exporter metadata files · '+(c.bytes/1024**3).toFixed(2)+' GB before compression';}
 function draftReady(active){if(active===undefined){const p=snapshot?.progress||{};active=!!snapshot?.running||['Preparing backup','Finding linked attachments','Checking backup changes','Unpacking archive','Integrating conversations'].includes(p.phase)||/^Packaging|^Uploading|^Copying/.test(p.phase||'');}$('backup-migrate').hidden=$('backup-route').value!=='desktop';$('backup-migrate').disabled=submitting||!$('backup-sync-folder').value.trim()||!Object.values(snapshot?.files||{}).some(f=>f.exists&&f.sha256);$('backup-run').disabled=submitting||($('backup-route').value==='desktop'?!$('backup-sync-folder').value.trim():!snapshot?.connection.connected||!snapshot?.config.folder_id);}
 async function poll(){clearTimeout(timer);try{render(await api('/api/backup/status'));}catch(e){if(open)$('backup-message').textContent=e.message;}timer=setTimeout(poll,open?1500:20000);}
 function sourceControls(){const follow=$('backup-follow-loader').checked;for(const id of ['backup-source','backup-browse-source','backup-up'])$(id).disabled=follow;$('backup-boundary').textContent=follow?'Follows Export folders, including its upward depth. Changes there apply to the next backup.':'Custom folder and upward traversal for backups.';}
 function routeControls(){const desktop=$('backup-route').value==='desktop';$('backup-desktop-connection').hidden=!desktop;$('backup-api-connection').hidden=desktop;$('backup-api-destination').hidden=desktop;$('backup-schedule-step').textContent=desktop?'3':'4';$('backup-run').textContent=desktop?'Copy ZIPs to Drive folder':'Back up to Drive now';draftReady();}
 async function save(schedule=false,localOnly=false){const old=snapshot?.config||{};await api('/api/backup/config',{follow_exporter:$('backup-follow-exporter').checked,source:$('backup-source').value.trim(),up:+$('backup-up').value,source_mode:$('backup-follow-loader').checked?'loader':'custom',route:$('backup-route').value,local_folder:$('backup-local-folder').value.trim(),sync_folder:$('backup-sync-folder').value.trim(),modes:$('backup-modes').value,include_formats:formats.filter(kind=>$('backup-include-'+kind).checked),cadence:$('backup-cadence').value,interval_hours:+$('backup-hours-number').value,idle_required:$('backup-idle-required').checked,ac_only:$('backup-ac-only').checked,auto_upload:$('backup-auto-upload').checked,cleanup_extras:$('backup-cleanup-extras').checked,idle_minutes:+$('backup-idle').value});if(!localOnly&&(schedule||$('backup-enabled').checked!==!!old.enabled)){await api('/api/backup/schedule',{enabled:$('backup-enabled').checked});}await poll();}
 async function showFolders(){const current=parents.at(-1);$('drive-folder-browser').hidden=false;$('drive-folder-location').textContent=current.name;$('drive-folder-back').disabled=parents.length===1;const box=$('drive-folder-list');box.replaceChildren(el('p','muted','Loading folders…'));const data=await api('/api/backup/folders?parent='+encodeURIComponent(current.id));box.replaceChildren();for(const folder of data.folders){const button=el('button','','▱ '+folder.name);button.onclick=safeRun(async()=>{parents.push(folder);await showFolders();});box.append(button);}if(!data.folders.length)box.append(el('p','muted','No subfolders. Use this folder or create a backup folder here.'));}
 function feedback(message,error=false){const box=$('backup-feedback');box.hidden=false;box.textContent=message;box.classList.toggle('error',error);}
 function bind(id,fn){$(id).onclick=async()=>{try{await fn();}catch(e){feedback(e.message,true);}};}
 async function detect(){const button=$('backup-detect');button.disabled=true;try{const data=await api('/api/backup/detect?refresh=1');for(const [id,values,selected] of [['source',data.source_candidates||[],$('backup-source').value],['drive',data.drive.roots||[],'']]){const select=$('backup-'+id+'-candidates');select.replaceChildren(new Option('Choose a detected location…',''));for(const value of values)select.add(new Option(value,value));if(values.includes(selected))select.value=selected;$('backup-'+id+'-options').hidden=!values.length;}if(!$('backup-source').value.trim()&&data.source){$('backup-source').value=data.source;$('backup-up').value=String(data.up);}if(!$('backup-sync-folder').value.trim()&&data.drive.sync_folder)$('backup-sync-folder').value=data.drive.sync_folder;feedback(data.drive.message+' Your existing folder choices are kept.');draftReady();}finally{button.disabled=false;}}
 function hourLabel(){const n=+$('backup-hours-number').value;$('backup-hours-label').textContent=n+' hour'+(n===1?'':'s');$('backup-cadence').value=n===24?'daily':n===168?'weekly':'custom';}
 $('backup-hours').oninput=()=>{$('backup-hours-number').value=$('backup-hours').value;hourLabel();};$('backup-hours-number').oninput=()=>{$('backup-hours').value=$('backup-hours-number').value;hourLabel();};$('backup-cadence').onchange=()=>{if($('backup-cadence').value!=='custom')$('backup-hours').value=$('backup-hours-number').value=$('backup-cadence').value==='weekly'?168:24;hourLabel();};
 bind('backup-cleanup',async()=>{await save(false,true);const r=await api('/api/backup/cleanup',{});feedback(r.deduplicated+' identical duplicates removed; '+r.retired+' distinct extra viewer ZIPs moved to recovery. Unrelated ZIPs were kept.');});
 bind('backup-detect',detect);
 bind('backup-open',async()=>{open=true;modal('backup-dialog');$('backup-feedback').hidden=true;await poll();fields(snapshot.config);await detect();});$('backup-dialog').addEventListener('close',()=>{open=false;poll();});
 $('backup-source-candidates').onchange=()=>{const value=$('backup-source-candidates').value;if(value){$('backup-follow-loader').checked=false;$('backup-source').value=value;$('backup-up').value='0';sourceControls();}};$('backup-drive-candidates').onchange=()=>{const value=$('backup-drive-candidates').value;if(value){$('backup-sync-folder').value=value.replace(/[\\/]+$/,'')+'/Offline Chat Viewer Backups';draftReady();}};
 $('backup-follow-loader').onchange=sourceControls;$('backup-route').onchange=routeControls;$('backup-sync-folder').oninput=()=>draftReady();
 bind('backup-preview',async()=>{await save(false,true);$('backup-counts').textContent='Checking file names and sizes…';const data=await api('/api/backup/preview'),c=data.counts;$('backup-counts').textContent=contentSummary(c);$('backup-boundary').textContent='Backup boundary: '+data.root;});
 for(const [button,input] of [['backup-browse-local','backup-local-folder'],['backup-browse-sync','backup-sync-folder']])bind(button,async()=>{const result=await api('/api/pick-folder',{path:$(input).value,destination:true,kind:input==='backup-sync-folder'?'drive':'local'});if(result.path)$(input).value=result.path;draftReady();});bind('backup-open-local',async()=>{const result=await api('/api/backup/open-local',{path:$('backup-local-folder').value.trim()});feedback('Opened local ZIP folder: '+result.path);});
 bind('backup-browse-source',async()=>{const result=await api('/api/pick-folder',{path:$('backup-source').value});if(result.path)$('backup-source').value=result.path;});
 $('drive-client-import').onclick=()=>$('drive-client-file').click();$('drive-client-file').onchange=safeRun(async()=>{const file=$('drive-client-file').files[0];if(!file)return;if(file.size>65536)throw Error('Choose the small Google Desktop app connection JSON.');await api('/api/backup/client',JSON.parse(await file.text()));$('drive-client-file').value='';await poll();toast('Google connection settings imported. Select Connect Google.');});
 bind('drive-connect',async()=>{await api('/api/backup/connect',{});await poll();});bind('drive-disconnect',async()=>{if(snapshot.config.enabled)await api('/api/backup/schedule',{enabled:false});await api('/api/backup/disconnect',{});await poll();fields(snapshot.config);});
 bind('drive-choose',showFolders);bind('drive-folder-back',async()=>{if(parents.length>1)parents.pop();await showFolders();});bind('drive-folder-select',async()=>{await api('/api/backup/select-folder',{id:parents.at(-1).id});$('drive-folder-browser').hidden=true;await poll();});
 bind('drive-new-folder',async()=>{const current=parents.at(-1);const folder=await api('/api/backup/create-folder',{name:'Chat archive backups',parent:current.id});await api('/api/backup/select-folder',{id:folder.id});$('drive-folder-browser').hidden=true;await poll();toast('Backup folder created and selected.');});
 bind('drive-folder-use',async()=>{const value=$('drive-folder-link').value.trim(),id=value.match(/\/folders\/([\w-]+)/)?.[1]||value;await api('/api/backup/select-folder',{id});await poll();});bind('backup-save',async()=>{await save(true);toast('Backup preferences saved.');});
 async function submit(path,body,localOnly=true){if(submitting)return;submitting=true;for(const id of ['backup-local','backup-run','backup-migrate','backup-retry'])$(id).disabled=true;try{if(path!=='/api/backup/retry')await save(false,localOnly);const result=await api(path,body);feedback(result.queued?'Request saved in the queue. Repeated requests are combined.':'Working on your ZIPs. Completed files and download links appear below.');}finally{submitting=false;await poll();}}
 bind('backup-migrate',()=>submit('/api/backup/migrate',{}));
 bind('backup-retry',()=>submit('/api/backup/retry',{}));
 bind('backup-run',()=>submit('/api/backup/run',{upload:true},false));bind('backup-local',()=>submit('/api/backup/run',{upload:false}));bind('backup-cancel',async()=>{await api('/api/backup/cancel',{});await poll();});
 bind('backup-import-zip',async()=>{const result=await api('/api/pick-archive',{});if(result.path){await api('/api/backup/import',{path:result.path,restore_settings:$('backup-restore-settings').checked});await poll();}});
 setTimeout(poll,2000);
})();
