'use strict';
window.MediaPlayer=(()=>{
 const make=(tag,cls='',text='')=>{const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;};
 const clock=s=>{s=Number.isFinite(s)?Math.max(0,s):0;return (s>=3600?Math.floor(s/3600)+':':'')+String(Math.floor(s/60)%60).padStart(s>=3600?2:1,'0')+':'+String(Math.floor(s%60)).padStart(2,'0');};
 function meter(canvas,analyser,isPlaying){const ctx=canvas.getContext('2d'),data=new Uint8Array(analyser.frequencyBinCount);let raf=0,last=0;function draw(stamp){raf=requestAnimationFrame(draw);if(stamp-last<50)return;last=stamp;const width=canvas.width,height=canvas.height;ctx.clearRect(0,0,width,height);if(isPlaying())analyser.getByteFrequencyData(data);else data.fill(0);const color=getComputedStyle(canvas).color;ctx.fillStyle=color;for(let i=0;i<48;i++){const magnitude=data[Math.floor(i*data.length/48)]/255,h=Math.max(3,magnitude*(height-6));ctx.globalAlpha=.25+magnitude*.75;ctx.fillRect(i*width/48,(height-h)/2,Math.max(2,width/48-4),h);}}raf=requestAnimationFrame(draw);return ()=>cancelAnimationFrame(raf);}
 function mount(host,options){
  const {url,name,kind,items=[],index=0,onSelect}=options,video=kind==='video',card=make('section','modern-media '+(video?'modern-video':'modern-audio')),head=make('header','modern-media-heading'),badge=make('span','modern-media-badge'),info=make('div'),title=make('strong','',name),subtitle=make('small','','Saved locally · '+(video?'Video':'Audio')),stage=make('div','modern-media-stage'),player=make(video?'video':'audio','attachment-player'),toolbar=make('div','modern-media-toolbar'),actions=make('div','modern-media-actions'),timeline=make('input','modern-media-seek'),time=make('span','modern-media-time','0:00 / 0:00'),status=make('p','modern-media-status','Ready to play'),list=make('div','modern-media-list');
  list.hidden=true;list.setAttribute('aria-label','Media in this thread');badge.append(ViewerIcons.svg(video?'video':'audio'));info.append(title,subtitle);head.append(badge,info);player.controls=false;player.preload='metadata';player.playsInline=true;player.setAttribute('aria-label',name);
  const icon=(label,glyph,action,cls='')=>{const b=make('button','modern-media-button '+cls);b.title=label;b.setAttribute('aria-label',label);ViewerIcons.set(b,glyph);b.onclick=()=>Promise.resolve(action()).catch(error=>status.textContent=error.message);return b;};
  let context=null,analyser=null,stopMeter=null,disposed=false;
  const canvas=make('canvas','modern-media-meter');canvas.width=720;canvas.height=80;canvas.setAttribute('aria-label','Live audio visualization');
  async function toggle(){if(player.paused){if(!video&&!context){try{context=new AudioContext();analyser=context.createAnalyser();analyser.fftSize=256;const source=context.createMediaElementSource(player);source.connect(analyser);analyser.connect(context.destination);stopMeter=meter(canvas,analyser,()=>!player.paused);}catch(error){subtitle.textContent='Saved audio · Visualization unavailable';console.warn(error.message);}}await context?.resume();await player.play();}else player.pause();}
  const play=icon('Play','play',toggle,'modern-media-play'),center=icon('Play video','play',toggle,'modern-media-center'),back=icon('Back 10 seconds','rewind',()=>player.currentTime=Math.max(0,player.currentTime-10)),forward=icon('Forward 10 seconds','forward',()=>player.currentTime=Math.min(player.duration||0,player.currentTime+10)),loop=icon('Repeat','repeat',()=>{player.loop=!player.loop;loop.setAttribute('aria-pressed',String(player.loop));}),mute=icon('Mute','volume',()=>player.muted=!player.muted),queue=icon('Media in this thread','playlist',()=>{list.hidden=!list.hidden;queue.setAttribute('aria-expanded',String(!list.hidden));});loop.setAttribute('aria-pressed','false');queue.setAttribute('aria-expanded','false');
  const previous=icon('Previous media','previous',()=>select(-1)),next=icon('Next media','next',()=>select(1)),available=items.map((item,i)=>({item,i})).filter(({item})=>item.available&&['audio','video','midi'].includes(item.kind));
  function select(delta){if(!available.length)return;const at=available.findIndex(entry=>entry.i===index),entry=available[(Math.max(0,at)+delta+available.length)%available.length];onSelect?.(entry.i);}
  previous.disabled=next.disabled=available.length<2;queue.disabled=!available.length;
  for(const entry of available){const b=make('button','modern-media-track'+(entry.i===index?' current':''));b.append(ViewerIcons.svg(entry.item.kind==='video'?'video':'audio'),make('span','',entry.item.name));b.onclick=()=>onSelect?.(entry.i);if(entry.i===index)b.setAttribute('aria-current','true');list.append(b);}
  const volume=make('input','modern-media-volume');volume.type='range';volume.min=0;volume.max=1;volume.step=.01;volume.value=1;volume.setAttribute('aria-label','Playback volume');volume.oninput=()=>{player.volume=+volume.value;player.muted=false;};
  timeline.type='range';timeline.min=0;timeline.max=1;timeline.step=.01;timeline.value=0;timeline.disabled=true;timeline.setAttribute('aria-label','Playback position');timeline.oninput=()=>{if(Number.isFinite(player.duration))player.currentTime=+timeline.value;};
  const speed=make('select','modern-media-speed');speed.setAttribute('aria-label','Playback speed');for(const value of [.5,.75,1,1.25,1.5,2]){const option=make('option','',value+'×');option.value=value;option.selected=value===1;speed.append(option);}speed.onchange=()=>player.playbackRate=+speed.value;
  actions.append(previous,back,play,forward,next,loop,time,mute,volume,speed,queue);
  if(video){const pip=icon('Picture in picture','pip',async()=>{if(document.pictureInPictureElement)await document.exitPictureInPicture();else await player.requestPictureInPicture();});pip.hidden=!document.pictureInPictureEnabled;const fullscreen=icon('Fullscreen','expand',()=>document.fullscreenElement?document.exitFullscreen():card.requestFullscreen());fullscreen.hidden=!document.fullscreenEnabled;actions.append(pip,fullscreen);stage.append(player,center);}
  else{stage.append(player,canvas);canvas.setAttribute('role','img');stage.append(make('small','modern-media-visual-label','Live audio'));}
  const sync=()=>{const playing=!player.paused;ViewerIcons.set(play,playing?'pause':'play');play.setAttribute('aria-label',playing?'Pause':'Play');play.title=playing?'Pause':'Play';ViewerIcons.set(center,playing?'pause':'play');center.setAttribute('aria-label',playing?'Pause video':'Play video');card.classList.toggle('playing',playing);const duration=Number.isFinite(player.duration)?player.duration:0;timeline.max=duration||1;timeline.disabled=!duration;timeline.value=player.currentTime||0;time.textContent=clock(player.currentTime)+' / '+clock(duration);timeline.setAttribute('aria-valuetext',time.textContent);ViewerIcons.set(mute,player.muted?'muted':'volume');mute.setAttribute('aria-label',player.muted?'Unmute':'Mute');volume.value=player.volume;status.textContent=player.ended?'Finished':playing?'Playing':player.currentTime?'Paused':'Ready to play';};
  for(const event of ['loadedmetadata','durationchange','timeupdate','play','pause','ended','volumechange'])player.addEventListener(event,sync);
  player.addEventListener('waiting',()=>status.textContent='Loading playback…');player.addEventListener('error',()=>{status.textContent='Playback unavailable for this file or codec. Open original to use another player.';play.disabled=center.disabled=true;});
  card.tabIndex=0;card.addEventListener('keydown',event=>{if(event.target.matches('input,select,button'))return;if(event.code==='Space'){event.preventDefault();toggle().catch(error=>status.textContent=error.message);}else if(event.key==='ArrowLeft'){event.preventDefault();back.click();}else if(event.key==='ArrowRight'){event.preventDefault();forward.click();}});
  toolbar.append(timeline,actions);card.append(head,stage,toolbar,status,list);host.append(card);player.src=url;sync();
  return ()=>{if(disposed)return;disposed=true;player.pause();stopMeter?.();player.removeAttribute('src');player.load();context?.close();};
 }
 return {mount,meter,clock};
})();
