'use strict';
// Rich formatting is scheduled only for messages approaching the viewport.
window.Reader=(()=>{
 const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 document.addEventListener('error',event=>{const img=event.target;if(img?.tagName!=='IMG')return;const card=img.closest('.image-thumbnail');if(!card||card.dataset.unavailableDecorated)return;const name=(img.alt||card.title||'Image').replace(/^Not saved locally:\s*/,'').replace(/\s*·\s*Open image$/,'');const icon=node('span','image-unavailable-icon'),warning=node('span','image-unavailable-warning','!'),info=node('span','image-unavailable-info');icon.setAttribute('aria-hidden','true');warning.setAttribute('aria-hidden','true');icon.append(ViewerIcons.svg('image'),warning);info.append(node('strong','',name),node('small','','Not saved locally'),node('small','','Image preview unavailable'));card.dataset.unavailableDecorated='true';card.classList.add('unavailable');card.setAttribute('aria-label','Image '+name+'. Not saved locally. Image preview unavailable. Activate to open image preview.');card.title=name+' · Not saved locally · Image preview unavailable';card.replaceChildren(icon,info);},true);
 class BoundedMap extends Map{constructor(limit){super();this.limit=limit;}set(key,value){super.delete(key);super.set(key,value);while(this.size>this.limit)this.delete(this.keys().next().value);return this;}}
 const states=new BoundedMap(512),sourceCache=new BoundedMap(128),renderCache=new BoundedMap(12);let renderBytes=0;let worker=null,ready=false,active=null,jobs=[],serial=0;
 let startupTimer=null;
 let colourWorker=null,colourReady=false,colourActive=null,colourJobs=[],colourTimer=null;
 function stopColour(){clearTimeout(colourTimer);if(colourActive){colourActive.resolve(null);colourActive=null;}for(const job of colourJobs.splice(0))job.resolve(null);colourWorker?.terminate();colourWorker=null;colourReady=false;}
 function runColour(){
  if(!colourJobs.length||colourActive)return;
  if(!colourWorker){colourWorker=new Worker('highlight-worker.js?v=1.1.4');colourTimer=setTimeout(stopColour,5000);colourWorker.onerror=stopColour;colourWorker.onmessage=e=>{if(e.data.ready){clearTimeout(colourTimer);colourReady=true;runColour();return;}if(e.data.error&&!e.data.id){stopColour();return;}if(colourActive&&e.data.id===colourActive.id){clearTimeout(colourTimer);const job=colourActive;colourActive=null;job.resolve(e.data.html||null);runColour();}};}
  if(!colourReady)return;
  while(colourJobs.length&&!colourJobs[0].root.isConnected)colourJobs.shift().resolve(null);
  if(!colourJobs.length)return;colourActive=colourJobs.shift();colourTimer=setTimeout(stopColour,1200);colourWorker.postMessage({id:colourActive.id,text:colourActive.text,language:colourActive.language});
 }
 function colour(text,root,language){return new Promise(resolve=>{colourJobs.push({id:++serial,text,language,root,resolve});runColour();});}
 function failWorker(message){clearTimeout(startupTimer);if(active){clearTimeout(active.timer);active.reject(Error(message));active=null;}for(const job of jobs.splice(0))job.reject(Error(message));worker?.terminate();worker=null;ready=false;}
 function cancel(){
  // Keep a booting/idle renderer warm when selection changes. Colouring never
  // owns the format queue while downloading its optional dependency.
  if(active){active.reject(Error('A different conversation was opened.'));active.cancelled=true;}
  for(const job of jobs.splice(0))job.reject(Error('A different conversation was opened.'));
  stopColour();
 }
 function preload(){if(worker)return;worker=new Worker('render-worker.js?v=1.1.4');startupTimer=setTimeout(()=>failWorker('Formatting renderer startup timed out.'),15000);
  worker.onmessage=e=>{if(e.data.ready){clearTimeout(startupTimer);ready=true;run();return;}if(e.data.startupError){failWorker(e.data.startupError);return;}
   if(active&&e.data.id===active.id){const job=active;clearTimeout(job.timer);active=null;if(!job.cancelled)e.data.error?job.reject(Error(e.data.error)):job.resolve(e.data.html);run();}};
  worker.onerror=()=>failWorker('Formatting worker could not load.');
 }
 function run(){if(!jobs.length||active)return;preload();if(!ready)return;while(jobs.length&&!jobs[0].root.isConnected)jobs.shift().reject(Error('Message is no longer visible.'));if(!jobs.length)return;active=jobs.shift();active.timer=setTimeout(()=>failWorker('This message needs more time to format.'),6000);worker.postMessage({id:active.id,text:active.text,mode:active.mode,language:active.language});}
 function parse(text,root,mode='markdown',language='plaintext'){const cacheKey=mode+'|'+language+'|'+text;if(renderCache.has(cacheKey))return Promise.resolve(renderCache.get(cacheKey));return new Promise((resolve,reject)=>{const done=resolve;resolve=html=>{if(html.length<2*1024*1024){renderCache.set(cacheKey,html);renderBytes=[...renderCache.entries()].reduce((n,[k,v])=>n+k.length+v.length,0);while(renderBytes>8*1024*1024&&renderCache.size){const [k,v]=renderCache.entries().next().value;renderCache.delete(k);renderBytes-=k.length+v.length;}}done(html);};const job={id:++serial,text,root,mode,language,resolve,reject};if(mode==='highlight')jobs.push(job);else if(root.dataset.priority)jobs.unshift(job);else{const enhancement=jobs.findIndex(j=>j.mode==='highlight');enhancement<0?jobs.push(job):jobs.splice(enhancement,0,job);}run();});}
 function enhanceCode(scope){if(!scope)return;
  for(const code of scope.querySelectorAll('.code-editor pre code[data-language]')){if(code.dataset.highlighted||code.dataset.highlighting||!code.isConnected)continue;
   const root=code.closest('.reader-content'),text=code.textContent,language=code.dataset.language;if(!root||text.length>65536||code.closest('.text-fold'))continue;const rect=code.getBoundingClientRect(),view=document.getElementById('scroller').getBoundingClientRect();if(!rect.height||rect.bottom<view.top-150||rect.top>view.bottom+150){colourObserver.observe(code);continue;}code.dataset.highlighting='1';
   colour(text,root,language).then(html=>{if(!code.isConnected||code.textContent!==text)return;if(html){const safe=sanitize(html,root._readerMessage?.[1]||'');code.replaceChildren(...safe.childNodes);}if(html){code.dataset.highlighted='1';colourObserver.unobserve(code);window.ArchiveFind?.refresh(false);}}).catch(()=>{}).finally(()=>{delete code.dataset.highlighting;});
  }
 }
 function online(url){try{const u=new URL(url);return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
 function icon(url,path,cid){const badge=node('span','source-icon');if(path&&!/^(?:[a-z]+:|\/\/)/i.test(path)){const img=node('img');img.src='/api/asset?'+new URLSearchParams({id:cid,path});img.alt='';img.onerror=()=>{img.remove();badge.textContent=new URL(url).hostname.replace(/^www\./,'')[0].toUpperCase();};badge.append(img);}else{badge.textContent=url?new URL(url).hostname.replace(/^www\./,'')[0].toUpperCase():'↗';}badge.setAttribute('aria-hidden','true');return badge;}
 function sourceAnchor(item,cid,cls='source-link'){const href=online(item.url),file=item.kind==='file'||cls.includes('saved-file');if(!href&&!file)return null;const a=node(href?'a':'button',cls+(file?' file-source':''));
  if(href){a.href=href;a.target='_blank';a.rel='noopener noreferrer';}else a.onclick=()=>showSources([item],cid);
  a.title=(item.title||'Saved file')+(href?'\n'+href:'');let badge;if(file){badge=node('span','source-icon file-icon','▤');badge.setAttribute('aria-hidden','true');}else badge=icon(href,item.icon,cid);
  a.append(badge,node('span','source-name',item.title||(href?new URL(href).hostname.replace(/^www\./,''):'Saved file')),node('span','source-arrow',href?'↗':'ⓘ'));return a;
 }
 function protect(text){text=RichMedia.blocks(text);const documentBlocks=DocumentCards.extract(text);text=documentBlocks.text;const extracted=SavedWidgets.extract(text),widgets=extracted.widgets; text=RichMedia.markup(extracted.text);const math=[],citations=[];let links={};text=text.split(/(```[\s\S]*?```|~~~[\s\S]*?~~~|`[^`\n]*`)/g).map((part,i)=>{if(i%2)return part;part=part.replace(/^\[\^?([^\]\n]+)\]:\s*(https?:\/\/\S+)(?:\s+"([^"\n]+)")?/gm,(_,ref,url,title)=>{links[ref]=[{url,title:title||new URL(url).hostname}];return '';});return part.replace(/\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\)|\$[^$\n]+\$/g,m=>'OFFLINEMATHPLACEHOLDER'+(math.push(m)-1)+'END').replace(/\ue200entity\ue202([\s\S]*?)\ue201/g,(raw,json)=>{try{const [category,label,url]=JSON.parse(json);return 'OFFLINECITEPLACEHOLDER'+(citations.push({type:'entity',label,category,url,refs:[]})-1)+'END';}catch{return raw;}}).replace(/\ue200(cite|filecite)\ue202([\s\S]*?)\ue201/g,(_,type,refs)=>'OFFLINECITEPLACEHOLDER'+(citations.push({type,refs:refs.split('\ue202').filter(Boolean)})-1)+'END').replace(/\ue200url\ue202([^\ue201]*?)\ue201/g,(_,body)=>{const parts=body.split('\ue202'),label=parts.shift()||'Saved source',refs=parts.filter(Boolean);if(online(label))refs.unshift(label);return 'OFFLINECITEPLACEHOLDER'+(citations.push({type:'url',label,refs})-1)+'END';}).replace(/\ue200genui\ue202(\{[\s\S]*?\})\ue201/g,(raw,json)=>{try{const d=JSON.parse(json).citation;if(!d)return raw;return 'OFFLINECITEPLACEHOLDER'+(citations.push({type:'cite',refs:d.refs||[d.ref]})-1)+'END';}catch{return raw;}});}).join('');return {text,math,citations,links,widgets,documents:documentBlocks.documents};}
 function typeset(root){for(const span of root.querySelectorAll('.math-pending')){
  if(!window.katex){if(!span.querySelector('.math-retry')){const retry=node('button','math-retry',typeof readers!=='undefined'&&readers?.failed?'Retry formula':'Render formula');retry.title='Load the bundled math renderer';retry.onclick=()=>{retry.textContent='Loading formula…';retry.disabled=true;loadReaders().math.then(()=>typeset(document)).catch(error=>{retry.title=error.message;retry.disabled=false;retry.textContent='Retry formula';});};span.append(retry);}continue;}
  try{let tex=span.dataset.tex;const parts=tex.split(/\\rightarrow\s*/);if(span.classList.contains('math-block')&&tex.length>150&&parts.length>=4&&parts.every(p=>/^\\text(?:bf)?\{[\s\S]*\}[.,;]?\s*$/.test(p.trim())))tex='\\begin{gathered}'+parts.map((p,i)=>(i?'\\rightarrow ':'')+p.trim()).join('\\\\')+'\\end{gathered}';katex.render(tex,span,{displayMode:span.classList.contains('math-block'),throwOnError:false,trust:false,maxExpand:1000});span.classList.remove('math-pending');}catch{}
 }}
 function citation(saved,links,cid){if(saved.type==='entity'){const label=String(saved.label||'Saved item'),matches=Object.values(links).flat().filter(item=>online(item.url)&&item.title?.toLocaleLowerCase().includes(label.toLocaleLowerCase()));if(online(saved.url))matches.unshift({url:saved.url,title:label});if(matches.length){const a=node('a','saved-entity',label);a.href=matches[0].url;a.target='_blank';a.rel='noopener noreferrer';a.title='Open saved source';return a;}const button=node('button','saved-entity',label);button.title='Show saved item details';button.onclick=()=>{const dialog=document.getElementById('sources-dialog'),list=document.getElementById('source-list'),search=node('a','source-link','Search web ↗');search.href='https://www.google.com/search?q='+encodeURIComponent(label);search.target='_blank';search.rel='noopener noreferrer';list.replaceChildren(node('strong','',label),node('p','muted',String(saved.category||'Saved item').replace(/_/g,' ')),node('p','muted','The export did not include a source URL for this item.'),search);dialog.showModal();};return button;}const wrap=node('span','citation-group'),items=[];for(const ref of saved.refs)for(const item of links[ref]||(online(ref)?[{url:ref,title:saved.label}]:[])){if((online(item.url)||item.kind==='file')&&!items.some(s=>(s.url||s.file_id||s.title)===(item.url||item.file_id||item.title)))items.push(item);}
  if(items.length){const first={...items[0],title:saved.type==='url'?saved.label:saved.type==='filecite'||items[0].kind==='file'?items[0].title:new URL(items[0].url).hostname.replace(/^www\./,'')};wrap.append(sourceAnchor(first,cid,saved.type==='filecite'?'saved-file source-link':saved.type==='url'?'saved-url source-link':'saved-citation source-link'));if(items.length>1){const more=node('button','saved-citation source-more','+'+(items.length-1));more.title='Show all saved sources';more.setAttribute('aria-label','Show '+items.length+' saved sources');more.onclick=()=>showSources(items,cid);wrap.append(more);}}
  else{const label=saved.type==='filecite'?saved.refs.map(ref=>{const n=ref.match(/file(\d+)/);return n?'File '+n[1]:'File reference';}).join(' · '):'Sources'+(saved.refs.length>1?' · '+saved.refs.length:'');const b=node('button',saved.type==='url'?'saved-url unresolved':'saved-citation',saved.type==='url'?saved.label:label);b.title='Saved references: '+saved.refs.join(', ');if(saved.type==='filecite'){b.classList.add('file-source');b.prepend(node('span','source-icon file-icon','▤'));}b.onclick=()=>showSources([],cid,saved.refs);wrap.append(b);}return wrap;
 }
 function showSources(items,cid,refs=[]){const dialog=document.getElementById('sources-dialog'),list=document.getElementById('source-list');list.replaceChildren();if(items.length){for(const item of items){if(online(item.url))list.append(sourceAnchor(item,cid));else{const card=node('section','file-source-details');card.append(node('strong','',item.title||'Saved file'),node('p','muted','The export saved this filename but no downloadable link.'));if(item.file_id)card.append(node('code','source-refs',item.file_id));list.append(card);}}}else{list.append(node('p','muted','This export saved the reference IDs but did not include filenames or URLs.'),node('code','source-refs',refs.join(', ')));}dialog.showModal();}
 async function resolveLinks(cid,refs,m){const key=cid+'|'+m.seq+'|'+(m.extras?.node_id||'')+'|'+refs.slice().sort().join('|');if(!sourceCache.has(key))sourceCache.set(key,api('/api/source-links',{id:cid,refs,seq:m.seq,node_id:m.extras?.node_id}).catch(()=>({})));return sourceCache.get(key);}
 function sanitize(html,cid){const doc=new DOMParser().parseFromString('<div>'+html+'</div>','text/html'),root=doc.body.firstElementChild;
  const allowed=new Set(['P','BR','H1','H2','H3','H4','H5','H6','STRONG','B','EM','I','DEL','S','UL','OL','LI','BLOCKQUOTE','PRE','CODE','TABLE','CAPTION','THEAD','TBODY','TFOOT','TR','TH','TD','HR','A','IMG','SPAN','DIV','INPUT','SUP','SUB','DETAILS','SUMMARY']);
  for(const n of [...root.querySelectorAll('*')]){if(!allowed.has(n.tagName)){if(['SCRIPT','STYLE','IFRAME','OBJECT','LINK'].includes(n.tagName))n.remove();else n.replaceWith(doc.createTextNode(n.textContent));continue;}const tokenClasses=n.tagName==='SPAN'?[...n.classList].filter(c=>/^hljs-[a-z_]+$/.test(c)):[];const attrs=[...n.attributes],href=n.getAttribute('href'),src=n.getAttribute('src'),alt=n.getAttribute('alt'),lang=(n.className||'').match(/(?:^|\s)language-([\w-]+)/)?.[1];for(const a of attrs)n.removeAttribute(a.name);
   if(n.tagName==='CODE'&&lang)n.dataset.language=lang;for(const cls of tokenClasses)n.classList.add(cls);
   if(n.tagName==='DETAILS'&&attrs.some(a=>a.name==='open'))n.open=true;
   if(['TD','TH'].includes(n.tagName)){const align=attrs.find(a=>a.name==='align')?.value||attrs.find(a=>a.name==='style')?.value.match(/text-align:\s*(left|center|right)/)?.[1];if(['left','center','right'].includes(align))n.style.textAlign=align;for(const attr of ['colspan','rowspan']){const v=+(attrs.find(a=>a.name===attr)?.value||0);if(v>1&&v<=100)n.setAttribute(attr,v);}}
   if(n.tagName==='A'&&href){if(href.startsWith('#'))n.href=href;else if(online(href)){n.href=online(href);n.target='_blank';n.rel='noopener noreferrer';n.classList.add('external-link');n.append(node('span','external-icon','↗'));}else if(/^(?:[A-Za-z]:[\\/]|\/[\w.-])/.test(href)&&/\.(?:jsonl|json|md)$/i.test(href)){n.dataset.indexedSource=href;}else if(!/^(?:[a-z]+:|\/\/)/i.test(href)){n.href='/api/asset?'+new URLSearchParams({id:cid,path:href});n.target='_blank';n.rel='noopener noreferrer';}}
   if(n.tagName==='IMG'){n.alt=alt||'Exported image';n.loading='lazy';if(src&&!/^(?:[a-z]+:|\/\/)/i.test(src))n.src='/api/asset?'+new URLSearchParams({id:cid,path:src});else n.replaceWith(RichMedia.group({images:[{title:alt||'Saved image',url:src||''}]},{cid}));}
   if(n.tagName==='INPUT'){n.type='checkbox';n.disabled=true;n.checked=attrs.some(a=>a.name==='checked');}
  }return root;
 }
 function foldState(details,key,initial=true){details.dataset.readerKey=key;details.open=states.has(key)?states.get(key):initial;details.addEventListener('toggle',()=>{states.set(key,details.open);});}
 function headings(root,key){const original=[...root.childNodes],fragment=document.createDocumentFragment(),stack=[{level:0,body:fragment}];let index=0;for(const n of original){if(/^H[1-6]$/.test(n.nodeName)){const level=+n.nodeName[1];while(stack.length>1&&stack.at(-1).level>=level)stack.pop();const details=node('details','section-fold'),summary=node('summary','section-summary'),body=node('div','section-body');summary.append(n);details.append(summary,body);foldState(details,key+'|heading:'+index++);stack.at(-1).body.append(details);stack.push({level,body});}else stack.at(-1).body.append(n);}root.replaceChildren(fragment);}
 function codeBlocks(root,key,presentation={},sourceText){let index=0;for(const pre of [...root.querySelectorAll('pre')]){
  const code=pre.querySelector('code'),display=code?.textContent??pre.textContent,isJson=presentation.kind==='code'&&String(presentation.language||'').toLowerCase()==='json'&&typeof sourceText==='string',raw=isJson?sourceText:display,details=node('details','code-fold'),summary=node('summary','code-header'),lang=code?.dataset.language||'Text',copy=node('button','code-copy','Copy'),codeKey=key+'|code:'+index++;
  copy.title='Copy saved block';copy.onclick=async e=>{e.preventDefault();e.stopPropagation();await navigator.clipboard.writeText(raw);copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy',1500);};
  const readable=CodePresentation.readable(code?.dataset.language,display,presentation.kind),displayLanguage=readable?'Text':({python:'Python',javascript:'JavaScript',typescript:'TypeScript',json:'JSON',bash:'Shell',shell:'Shell',plaintext:'Text'}[lang.toLowerCase()]||lang);if(readable){details.classList.add('text-fold');if(code){code.textContent=display;delete code.dataset.language;}}
  if(presentation.kind==='output'){details.classList.add('output-fold');pre.classList.add('execution-output');}
  summary.append(node('span','code-symbol',readable?'≡':presentation.kind==='output'?'›_':'‹/›'),node('strong','code-language',presentation.kind==='output'?(presentation.label||'STDOUT/STDERR'):displayLanguage),node('span','code-lines',display.split('\n').length+' lines'));
  const editor=node('div','code-editor');editor.tabIndex=0;editor.setAttribute('role','region');editor.setAttribute('aria-label',readable?'Saved text':displayLanguage+' code');
  if(presentation.kind!=='output'&&!readable){
   const gutter=node('div','code-gutter',display.split('\n').map((_,i)=>i+1).join('\n')),wrap=node('button','code-wrap','Wrap');gutter.setAttribute('aria-hidden','true');editor.append(gutter);
   const applyWrap=value=>{editor.classList.toggle('wrap-code',value);wrap.setAttribute('aria-pressed',String(value));states.set(codeKey+'|wrap',value);};applyWrap(states.get(codeKey+'|wrap')===true);
   wrap.title='Toggle code line wrapping';wrap.onclick=e=>{e.preventDefault();e.stopPropagation();applyWrap(!editor.classList.contains('wrap-code'));};summary.append(wrap);
   if(isJson&&code){const view=node('button','code-json-view','Raw'),formatted=code.innerHTML;let rawView=false;
    const applyView=value=>{rawView=value;delete code.dataset.highlighted;if(value)code.textContent=raw;else code.innerHTML=formatted;const lines=code.textContent.split('\n');gutter.textContent=lines.map((_,i)=>i+1).join('\n');summary.querySelector('.code-lines').textContent=lines.length+' lines';view.textContent=value?'Formatted':'Raw';view.title=value?'Show readable JSON':'Show original exported JSON';view.setAttribute('aria-pressed',String(value));states.set(codeKey+'|raw',value);enhanceCode(details);};applyView(states.get(codeKey+'|raw')===true);view.onclick=e=>{e.preventDefault();e.stopPropagation();applyView(!rawView);};summary.append(view);
   }
  }
  summary.append(copy);pre.replaceWith(details);editor.append(pre);details.append(summary,editor);foldState(details,codeKey,readable);
 }}
 function tables(root,key){let index=0;for(const table of [...root.querySelectorAll('table')]){if(table.closest('.chart-data,.rich-dil-layout'))continue;const cols=Math.max(...[...table.rows].map(r=>[...r.cells].reduce((n,c)=>n+(c.colSpan||1),0))),rows=table.tBodies[0]?.rows.length||Math.max(0,table.rows.length-1),card=node('section','table-card'),bar=node('div','table-toolbar'),viewport=node('div','table-wrap'),toggle=node('button','table-toggle','▾'),copy=node('button','','Copy'),expand=node('button','','Expand ↗'),tableKey=key+'|table:'+index++;
    viewport.tabIndex=0;viewport.setAttribute('role','region');viewport.setAttribute('aria-label','Scrollable table');table.style.setProperty('--table-min-width',(cols>=3?104+(cols-1)*224:Math.max(480,cols*240))+'px');table.dataset.columns=cols;
    const fit=node('button','table-fit','Wide'),compact=node('button','table-compact','Compact');
    const isIndex=/^(#|no\.?|index|id)$/i.test(table.rows[0]?.cells[0]?.textContent.trim()||'');if(isIndex)table.dataset.index='1';
    const applyFit=wide=>{table.classList.toggle('fit-table',!wide);fit.textContent=wide?'Fit':'Wide';fit.title=wide?'Fit all columns to the reading width':'Use wider columns with horizontal scrolling';fit.setAttribute('aria-pressed',String(!wide));states.set(tableKey+'|wide',wide);};applyFit(states.has(tableKey+'|wide')?states.get(tableKey+'|wide'):false);fit.onclick=()=>applyFit(table.classList.contains('fit-table'));
    const applyCompact=value=>{table.classList.toggle('compact-table',value);compact.setAttribute('aria-pressed',String(value));states.set(tableKey+'|compact',value);};applyCompact(states.get(tableKey+'|compact')===true);compact.title='Toggle compact row spacing';compact.onclick=()=>applyCompact(!table.classList.contains('compact-table'));

    toggle.title='Collapse table';toggle.setAttribute('aria-label','Collapse table');toggle.onclick=()=>{viewport.hidden=!viewport.hidden;states.set(tableKey,!viewport.hidden);toggle.textContent=viewport.hidden?'▸':'▾';toggle.setAttribute('aria-expanded',String(!viewport.hidden));toggle.setAttribute('aria-label',viewport.hidden?'Expand table':'Collapse table');};viewport.hidden=states.get(tableKey)===false;toggle.textContent=viewport.hidden?'▸':'▾';toggle.setAttribute('aria-expanded',String(!viewport.hidden));card.dataset.readerKey=tableKey;
    copy.title='Copy table as tab-separated text';copy.onclick=async()=>{const text=[...table.rows].map(r=>[...r.cells].map(c=>c.innerText.trim()).join('\t')).join('\n');await navigator.clipboard.writeText(text);copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy',1500);};expand.title='Open wide table view';expand.onclick=()=>expandTable(table,viewport,expand);
    bar.append(toggle,node('span','table-label','Table'),node('span','table-size',rows+' rows · '+cols+' columns'),fit,compact,copy,expand);table.replaceWith(card);viewport.append(table);card.append(bar,viewport);}}
 let restoreTable=null;
 function expandTable(table,home,button){const dialog=document.getElementById('table-dialog'),box=document.getElementById('table-content'),scroller=document.getElementById('scroller'),top=scroller.scrollTop,left=home.scrollLeft,vertical=home.scrollTop;restoreTable=()=>{home.append(table);home.scrollLeft=left;home.scrollTop=vertical;scroller.scrollTop=top;button.focus({preventScroll:true});};box.replaceChildren(table);dialog.showModal();}
 function closeTable(){const dialog=document.getElementById('table-dialog');if(dialog?.open){restoreTable?.();restoreTable=null;dialog.close();}}
 function bind(){document.getElementById('messages').addEventListener('toggle',e=>{if(e.target.open)enhanceCode(e.target);},true);document.getElementById('table-dialog').addEventListener('close',()=>{restoreTable?.();restoreTable=null;});document.getElementById('table-wrap-toggle').onchange=e=>document.getElementById('table-content').classList.toggle('no-wrap',!e.target.checked);document.getElementById('table-density').onchange=e=>document.getElementById('table-content').classList.toggle('compact',e.target.value==='compact');}
 function setAll(open){for(const d of document.querySelectorAll('#messages details')){d.open=open;if(d.dataset.readerKey)states.set(d.dataset.readerKey,open);}for(const card of document.querySelectorAll('#messages .table-card')){const viewport=card.querySelector('.table-wrap');if(viewport.hidden===open)card.querySelector('.table-toggle').click();}}
 let textLoads=0,textWaiting=[];
 async function fullText(m,cid,leaf){if(m.text_complete!==false)return m.text;if(m._fullPromise)return m._fullPromise;const gen=S.generation,controller=S.activeController;m._fullPromise=(async()=>{if(textLoads>=2)await new Promise(resolve=>textWaiting.push(resolve));textLoads++;try{while(m.text_complete===false){if(S.selected?.id!==cid||gen!==S.generation||controller?.signal.aborted)throw Error('A different conversation was opened.');const p=new URLSearchParams({id:cid,seq:m.seq,offset:m.text_next,bytes:65536,...(leaf?{leaf}:{})}),part=await api('/api/message-text?'+p,undefined,{controller});if(part.next_offset<=m.text_next&& !part.complete)throw Error('Message fragment made no progress.');m.text+=part.text;m.text_next=part.next_offset;m.text_complete=part.complete;}return m.text;}finally{textLoads--;textWaiting.shift()?.();}})();try{return await m._fullPromise;}finally{delete m._fullPromise;}}
 async function format(root,m,cid,key){if(root.dataset.busy||root.dataset.formatted)return;root.dataset.busy='1';let status=root.querySelector('.format-status');const partial=m.text_complete===false;try{const presentation=m.extras?.presentation||{},mode=presentation.kind==='code'?'code':presentation.kind==='output'?'output':'markdown',tokens=mode==='markdown'?protect(m.text):{text:m.text,math:[],citations:[],links:{}},html=await parse(tokens.text,root,mode,(presentation.language||'plaintext').toLowerCase().replace(/[^\w+-]/g,'')),rich=sanitize(html,cid),sources={...tokens.links,...(m.extras?.sources||{})},walker=document.createTreeWalker(rich,NodeFilter.SHOW_TEXT),texts=[];while(walker.nextNode())texts.push(walker.currentNode);
    const unresolved=[];for(const textNode of mode==='markdown'?texts:[]){const matcher=/OFFLINE(MATH|CITE|WIDGET)PLACEHOLDER(\d+)END/g;let match,last=0,fragment=document.createDocumentFragment(),found=false;while((match=matcher.exec(textNode.textContent))){found=true;fragment.append(document.createTextNode(textNode.textContent.slice(last,match.index)));last=matcher.lastIndex;if(match[1]==='WIDGET'){fragment.append(SavedWidgets.render(tokens.widgets[+match[2]],{cid,seq:m.seq,index:+match[2]}));}else if(match[1]==='MATH'){const raw=tokens.math[+match[2]],display=raw.startsWith('$$')||raw.startsWith('\\['),cut=raw.startsWith('$')&&!display?1:2,span=node('span',(display?'math-block':'math-inline')+' math-pending',raw);span.dataset.tex=raw.slice(cut,-cut);fragment.append(span);}else{const saved=tokens.citations[+match[2]],chip=citation(saved,sources,cid);fragment.append(chip);if(saved.refs.some(ref=>!sources[ref]))unresolved.push({chip,saved});}}if(found){fragment.append(document.createTextNode(textNode.textContent.slice(last)));textNode.replaceWith(fragment);}}
    if(mode==='markdown'){DocumentCards.decorate(rich,tokens.documents,partial);let documentIndex=0;for(const body of rich.querySelectorAll('.document-body'))headings(body,key+'|document:'+documentIndex++);headings(rich,key);}codeBlocks(rich,key,presentation,m.text);if(partial)for(const b of rich.querySelectorAll('.code-copy')){b.textContent='Copy visible';b.title='Copy the loaded portion of code';}tables(rich,key);let i=0;for(const d of rich.querySelectorAll('details:not([data-reader-key])')){d.classList.add('export-fold');foldState(d,key+'|export:'+i++,d.open);}typeset(rich);
    if(!root.isConnected||S.selected?.id!==cid)return;window.NativeFileLinks?.decorate(rich);
    const scroller=document.getElementById('scroller'),oldHeight=root.getBoundingClientRect().height,above=root.getBoundingClientRect().bottom<scroller.getBoundingClientRect().top,atBottom=scroller.scrollHeight-scroller.scrollTop-scroller.clientHeight<90;const positions=[...root.querySelectorAll('[data-reader-key]')].map(n=>({key:n.dataset.readerKey,el:n.querySelector('.code-editor,.table-wrap')})).filter(p=>p.el).map(p=>({key:p.key,top:p.el.scrollTop,left:p.el.scrollLeft}));root.replaceChildren(rich);ThreadImages.bindRendered(root,m,cid,root._readerLeaf);ThreadAttachments.catalog(cid,root._readerLeaf).then(data=>{if(root.isConnected)ThreadImages.cleanReferences(root,data.attachments.filter(i=>i.sequences.includes(m.seq)));}).catch(()=>{});const replacements=new Map([...root.querySelectorAll('[data-reader-key]')].map(n=>[n.dataset.readerKey,n]));for(const p of positions){const el=replacements.get(p.key)?.querySelector('.code-editor,.table-wrap');if(el){el.scrollTop=p.top;el.scrollLeft=p.left;}}root.classList.remove('plain-message');root.dataset.formatted='1';root._renderedLength=m.text.length;delete root.dataset.formatAttempts;observer.unobserve(root);enhanceCode(root);if(partial){status=node('button','format-status','Showing available content · Loading rest…');root.append(status);}if(root.isConnected&&above)scroller.scrollTop+=root.getBoundingClientRect().height-oldHeight;else if(root.isConnected&&atBottom&&!S.searchNavigating)scroller.scrollTop=scroller.scrollHeight;
    if(unresolved.length)resolveLinks(cid,[...new Set(unresolved.flatMap(x=>x.saved.refs))],m).then(links=>{for(const {chip,saved} of unresolved){if(saved.refs.some(ref=>links[ref]))chip.replaceWith(citation(saved,{...sources,...links},cid));}});
    if(partial){fullText(m,cid,root._readerLeaf).then(()=>{delete root.dataset.formatted;if(root.isConnected&&S.selected?.id===cid)format(root,m,cid,key);}).catch(error=>{if(status&&root.isConnected){status.textContent='Showing available content · Retry loading rest';status.title=error.message;status.onclick=()=>{delete root.dataset.formatted;format(root,m,cid,key);};}});}
   }catch(error){if(status){const attempts=+(root.dataset.formatAttempts||0)+1;root.dataset.formatAttempts=attempts;status.title=error.message;status.onclick=()=>{delete root.dataset.formatAttempts;format(root,m,cid,key);};
    if(attempts<=2){status.textContent='Formatting delayed · Retrying automatically…';clearTimeout(root._formatRetry);root._formatRetry=setTimeout(()=>{if(root.isConnected&&!root.dataset.formatted)format(root,m,cid,key);},350*attempts);}
    else status.textContent='Renderer unavailable · Retry formatting';
   }}finally{delete root.dataset.busy;}}
 const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){const root=entry.target;if(root._readerMessage&&root.isConnected)format(root,...root._readerMessage);}}, {root:document.getElementById('scroller'),rootMargin:'800px'});
 function create(m,cid,key){const root=node('div','plain-message reader-content'),text=node(m.extras?.presentation?.kind?'pre':'div','plain-text',m.extras?.presentation?.kind?m.text:RichMedia.markup(SavedWidgets.extract(m.text).text).replace(/OFFLINEWIDGETPLACEHOLDER\d+END/g,'[Loading saved widget…]')),status=node('button','format-status',m.text_complete===false?'Long message · Load complete message':'Formatting…');root.append(text,status);root._readerLeaf=S.leaf;root._readerMessage=[m,cid,key];status.onclick=()=>format(root,m,cid,key);observer.observe(root);return root;}
 const colourObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)enhanceCode(entry.target.closest('.reader-content'));},{root:document.getElementById('scroller'),rootMargin:'150px'});
 function release(nodes){ThreadAttachments.release(nodes);ThreadImages.release(nodes);for(const n of nodes)for(const root of n.querySelectorAll('.reader-content')){observer.unobserve(root);for(const code of root.querySelectorAll('code[data-language]'))colourObserver.unobserve(code);clearTimeout(root._formatRetry);}}
 function resume(nodes){ThreadAttachments.resume(nodes);ThreadImages.resume(nodes);for(const n of nodes)enhanceCode(n);for(const n of nodes)for(const root of n.querySelectorAll('.reader-content:not([data-formatted])')){observer.observe(root);requestAnimationFrame(()=>{const view=document.getElementById('scroller').getBoundingClientRect(),rect=root.getBoundingClientRect();if(root.isConnected&&rect.top<view.bottom+800&&rect.bottom>view.top-800)format(root,...root._readerMessage);});}}
 function prioritize(article){for(const root of article.querySelectorAll('.reader-content')){root.dataset.priority='1';jobs.sort((a,b)=>(b.root===root)-(a.root===root));format(root,...root._readerMessage);}}

 async function ensure(article){const root=article.querySelector('.reader-content');if(!root)return;const [m,cid,key]=root._readerMessage;root.dataset.priority='1';await fullText(m,cid,root._readerLeaf);const until=Date.now()+18000;while(root.dataset.busy&&Date.now()<until)await new Promise(r=>setTimeout(r,25));if(root._renderedLength!==m.text.length)delete root.dataset.formatted;await format(root,m,cid,key);if(!root.dataset.formatted)throw Error('Message formatting is delayed. Try the match again.');}
 async function preview(root,text,cid,leaf,attachment){const tokens=protect(text),html=await parse(tokens.text,root),rich=sanitize(html,cid);if(!root.isConnected)return;const walker=document.createTreeWalker(rich,NodeFilter.SHOW_TEXT),texts=[];while(walker.nextNode())texts.push(walker.currentNode);for(const t of texts){const re=/OFFLINE(MATH|CITE|WIDGET)PLACEHOLDER(\d+)END/g;let m,last=0,found=false,fragment=document.createDocumentFragment();while((m=re.exec(t.textContent))){found=true;fragment.append(document.createTextNode(t.textContent.slice(last,m.index)));last=re.lastIndex;if(m[1]==='MATH'){const raw=tokens.math[+m[2]],display=raw.startsWith('$$')||raw.startsWith('\\['),cut=raw.startsWith('$')&&!display?1:2,span=node('span',(display?'math-block':'math-inline')+' math-pending',raw);span.dataset.tex=raw.slice(cut,-cut);fragment.append(span);}else if(m[1]==='CITE')fragment.append(citation(tokens.citations[+m[2]],tokens.links,cid));else fragment.append(SavedWidgets.render(tokens.widgets[+m[2]],{cid,seq:0,index:+m[2]}));}if(found){fragment.append(document.createTextNode(t.textContent.slice(last)));t.replaceWith(fragment);}}for(const img of rich.querySelectorAll('img[src]')){const path=new URL(img.src,location.href).searchParams.get('path');if(path)img.src='/api/thread-attachments/relative?'+new URLSearchParams({id:cid,attachment,path,...(leaf?{leaf}:{})});}DocumentCards.decorate(rich,tokens.documents);typeset(rich);root.replaceChildren(rich);}
 return {preview,ensure,preload,create,typeset,bind,setAll,closeTable,fullText,foldState,cancel,release,resume,prioritize};
})();
