'use strict';
window.RichMedia=(()=>{
 const n=(tag,cls='',text='')=>{const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;};
 const decode=s=>String(s).replace(/&(?:amp|quot|apos|lt|gt);/g,x=>({'&amp;':'&','&quot;':'"','&apos;':"'",'&lt;':'<','&gt;':'>'})[x]);
 function attributes(tag){const out={};tag.replace(/([\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|\{([^}]*?)\})/g,(_,key,a,b,c)=>{out[key.toLowerCase()]=decode(a??b??c);return '';});return out;}
 function blocks(text){return text.split(/(```[\s\S]*?(?:```|$)|~~~[\s\S]*?(?:~~~|$)|`[^`\n]*`)/g).map((part,i)=>{if(i%2)return part;const token=images=>'\n\ue200image_group\ue202'+JSON.stringify({images})+'\ue201\n',item=content=>{const tag=content.match(/<AsyncImage\b[^>]*?\/>/i);if(!tag)return null;const a=attributes(tag[0]),title=content.match(/\*\*([^\n]*?)\*\*/)?.[1]||a.alt||a.title||a.query||'Saved image',description=content.match(/<caption>([\s\S]*?)<\/caption>/i)?.[1]?.trim()||'';return {title,description,ref:a.ref,query:a.query,src:a.src||a.url||'',aspect_ratio:a.aspectratio,fit:a.fit};};return part.replace(/<grid\b[^>]*>([\s\S]*?)<\/grid>/gi,(raw,body)=>{const images=[...body.matchAll(/<grid-item\b[^>]*>([\s\S]*?)<\/grid-item>/gi)].map(m=>item(m[1])).filter(Boolean);return images.length?token(images):raw;}).replace(/<AsyncImage\b[^>]*?\/>(?:[ \t]*\r?\n){0,3}(?:[ \t]*\*\*[^\n]*?\*\*)?/gi,raw=>token([item(raw)]));}).join('');}
 function markup(text){return text.split(/(```[\s\S]*?(?:```|$)|~~~[\s\S]*?(?:~~~|$)|`[^`\n]*`)/g).map((part,i)=>i%2?part:part.replace(/<(Entity|Cite|Link)\b[^>]*?\/>/gi,(raw,type)=>{const a=attributes(raw);if(type.toLowerCase()==='entity'){const label=a.value||a.name||a.title;if(!label)return raw;return '\ue200entity\ue202'+JSON.stringify([a.category||a.type||'Saved item',label,a.url||a.href||''])+'\ue201';}if(type.toLowerCase()==='cite'){let refs=a.ref?[a.ref]:[];try{if(a.refs)refs=JSON.parse(a.refs);}catch{return raw;}return Array.isArray(refs)?'\ue200cite\ue202'+refs.filter(x=>typeof x==='string').slice(0,64).join('\ue202')+'\ue201':raw;}const url=a.url||a.href||'',label=(a.title||a.label||url).replace(/[\[\]\\|]/g,'\\$&');return /^https?:\/\//i.test(url)?'['+label+'](<'+url.replace(/[<>\s]/g,x=>encodeURIComponent(x))+'>)':label;}).replace(/<caption>([\s\S]*?)<\/caption>/gi,(_,caption)=>'\n\n'+caption+'\n\n').replace(/<text\b[^>]*>([\s\S]*?)<\/text>/gi,'$1').replace(/^\s*\*{4}\s*$/gm,'' )).join('');}
 function columns(count){return count<=3?Math.max(1,count):count===4?2:count<=9?3:4;}
 function combine(text,widgets){
  const matches=[...text.matchAll(/(^|\n)(#{1,6}\s+([^\n]+)\n[ \t\r\n]*)(OFFLINEWIDGETPLACEHOLDER(\d+)END)/g)].filter(m=>widgets[+m[5]]?.image_group);
  const runs=[];let run=[];for(const m of matches){const previous=run.at(-1),between=previous?text.slice(previous.index+previous[0].length,m.index):'';if(previous&&(/\n\s*#{1,6}\s|OFFLINEWIDGETPLACEHOLDER|```|~~~/.test(between)||between.length>1200)){if(run.length>1)runs.push(run);run=[];}run.push(m);}if(run.length>1)runs.push(run);
  for(const batch of runs.reverse()){const first=batch[0],last=batch.at(-1);let end=last.index+last[0].length;const after=text.slice(end).match(/^\s*\n([^\n#][^\n]*(?:\n(?!\s*\n|#)[^\n]+)*)/),lastNote=after&&after[0].length<1200?after[1]:'';if(lastNote)end+=after[0].length;const sections=batch.map((m,i)=>{const tail=i<batch.length-1?text.slice(m.index+m[0].length,batch[i+1].index).trim():lastNote;return {...widgets[+m[5]].image_group,title:m[3].replace(/\*\*/g,''),description:tail};});const index=widgets.push({image_group:{title:'Image collection',sections}})-1;text=text.slice(0,first.index)+(first[1]||'')+'\nOFFLINEWIDGETPLACEHOLDER'+index+'END\n'+text.slice(end);}
  return {text,widgets};
 }
 function safeUrl(value){if(!value)return '';try{const u=new URL(value,location.href);return /^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
 function inline(host,text){const pattern=/\[([^\]]+)\]\((?:<([^>]+)>|([^\s)]+))\)|\*\*([^*]+)\*\*|\*([^*]+)\*/g;let last=0;for(const match of String(text).matchAll(pattern)){host.append(document.createTextNode(text.slice(last,match.index)));last=match.index+match[0].length;if(match[1]){const url=safeUrl(match[2]||match[3]);if(url){const a=n('a','',match[1]);a.href=url;a.target='_blank';a.rel='noopener noreferrer';host.append(a);}else host.append(document.createTextNode(match[1]));}else host.append(n(match[4]?'strong':'em','',match[4]||match[5]));}host.append(document.createTextNode(text.slice(last)));}
 function group(spec,context={}){
  const card=n('section','saved-widget rich-media-group'),sections=n('div','rich-media-sections'),status=n('p','rich-media-status'),head=n('header','rich-media-heading');
  head.append(n('h4','widget-title',spec.title||'Image collection'),status);card.append(head,sections);
  let loaded=0,waiting=0,missing=0;const groups=Array.isArray(spec.sections)?spec.sections.slice(0,24):[spec];sections.style.setProperty('--rich-columns',columns(groups.length));
  const update=()=>status.textContent=`${loaded} loaded · ${waiting} loading · ${missing} unavailable`;
  for(const section of groups){const box=n('section','rich-media-section'),grid=n('div','rich-media-grid');if(spec.sections)box.append(n('h5','',section.title||'Saved images'));const notes=section.description?n('p','rich-media-description'):null;if(notes)inline(notes,section.description);box.append(grid);if(notes)box.append(notes);sections.append(box);
  let source=section.images||section.items||section.results||section.query||[];if(!Array.isArray(source))source=[source];grid.style.setProperty('--rich-columns',columns(Math.min(source.length,24)));
  if(!source.length)source=[{title:'Image preview unavailable'}];
  for(const entry of source.slice(0,24)){
   const item=typeof entry==='string'?{title:entry}:entry||{},figure=n('figure','rich-media-card'),preview=n('div','rich-media-preview'),caption=n('figcaption'),title=item.title||item.caption||item.query||'Saved image',raw=item.image_url?.url||item.image_url||item.url||item.src||'',href=safeUrl(item.source_url||item.link||(/^(?:https?:|\/\/)/i.test(raw)?raw:''));
   if(source.length===1)preview.style.aspectRatio='4 / 3';figure.append(preview,caption);caption.append(n('strong','',title));if(item.description)caption.append(n('small','',item.description));
   const fallback=message=>{preview.classList.remove('loading');preview.replaceChildren(ViewerIcons.svg('image'),n('strong','','Preview unavailable'),n('small','',message));};
   const resolved=raw&&!/^(?:[a-z]+:|\/\/)/i.test(raw)&&context.cid?'/api/asset?'+new URLSearchParams({id:context.cid,path:raw}):raw,url=safeUrl(resolved),local=url&&new URL(url).origin===location.origin&&/^\/api\/(?:asset|thread-images\/content|thread-attachments\/relative)\?/.test(new URL(url).pathname+'?');
   if(local){waiting++;const img=n('img');img.alt=title;img.loading='lazy';img.decoding='async';preview.classList.add('loading');preview.append(img);img.onload=()=>{waiting--;loaded++;preview.classList.remove('loading');update();};img.onerror=()=>{waiting--;missing++;fallback('The saved image could not be loaded.');update();};img.src=url;if(context.cid){img.tabIndex=0;img.setAttribute('role','button');img.title='Open image viewer';const open=()=>ThreadImages.open(context.cid,raw,img,S.leaf).catch(e=>toast(e.message));img.onclick=open;img.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}};}}
   else{missing++;fallback(raw?'This external image was not saved for offline preview.':item.ref?'The saved image reference has no local preview.':'The image search is saved; its image files are unavailable.');}
   if(href||local){const a=n('a','','Open source ↗');a.href=href||url;a.target='_blank';a.rel='noopener noreferrer';caption.append(a);}grid.append(figure);
  }
  }
  const details=n('details','widget-source'),summary=n('summary','','Saved source'),pre=n('pre');pre.textContent=JSON.stringify(spec,null,2);details.append(summary,pre);card.append(details);update();return card;
 }
 return {markup,group,combine,columns,blocks};
})();
