'use strict';
window.SidebarLayout=(()=>{
 let draft,dragRule=null,dragFolder=null;
 const cfg=()=>SidebarModel.config(S.settings.sidebarLayout);
 async function persist(next){await saveSetting('sidebarLayout',next);}
 function saveView(next){S.settings.sidebarLayout=next;renderSidebar();return persist(next);}
 function icon(name){return ViewerIcons.svg(name);}
 function control(label,name,fn){const b=el('button','layout-control');b.type='button';b.title=label;b.setAttribute('aria-label',label);b.append(icon(name));b.onclick=safeRun(fn);return b;}
 function closed(n,c){return c.closed.includes(n.key)||n.folder&&c.collapsedFolders&&!c.opened.includes(n.key);}
 function assignment(n,c){if(n.rule==='projects'||n.rule==='folders'||n.rule==='work'||n.rule==='codex'||n.rule==='chat'||n.rule==='recent')return null;if(n.category!==null&&n.category!==undefined)return {category:n.category,trashed:0};if(n.rule==='pins')return {pinned:1,trashed:0};if(n.rule==='bookmarks')return {bookmarked:1,trashed:0};return null;}
 function canReorder(source,target,n){return source&&target&&source.project===target.project&&(source.category||'')===(target.category||'')&&kind(source)===kind(target)&&!!source.pinned===!!target.pinned&&!!source.bookmarked===!!target.bookmarked&&n.rows.some(c=>c.id===source.id);}
 function row(c,n,depth){
  const r=sidebarRows.get(c.id)||el('div');sidebarRows.set(c.id,r);r.className='chat-row layout-chat'+(c.id===S.selected?.id?' selected':'')+(c.color?' colored':'')+(c.sticky?' sticky':'');r.style.setProperty('--level',depth);r.style.setProperty('--chat-color',c.color||'var(--accent)');r.style.setProperty('--chat-tint',c.color?c.color+'18':'transparent');r.dataset.id=c.id;r.replaceChildren();
  const open=el('button'),text=el('span','layout-chat-text'),title=el('span','catalog-row-title',displayTitle(c));text.append(title);const info=[c.project?'Project · '+c.project:'',c.category?'Folder · '+c.category:'',c.bookmarked&&n.rule!=='bookmarks'?'Bookmarked':'',kind(c)!=='chat'?kind(c)==='codex'?'Codex':'Work':''].filter(Boolean);if(info.length)text.append(el('small','layout-chat-context',info.join(' · ')));open.append(text);open.title=displayTitle(c)+(info.length?'\n'+info.join('\n'):'');open.onclick=safeRun(()=>openChat(c.id));const more=el('button','row-menu');ViewerIcons.set(more,'more');more.title='Organize '+displayTitle(c);more.setAttribute('aria-label',more.title);more.onclick=()=>ChatControls.open(c,more);r.append(open,more);CatalogControls.row(r,c);
  r.draggable=true;r.ondragstart=e=>{S.sidebarDragging=true;e.dataTransfer.setData('text/plain',c.id);ChatControls.dragging(true,c.id);r.classList.add('dragging');};r.ondragend=()=>{S.sidebarDragging=false;r.classList.remove('dragging');ChatControls.dragging(false);if(S.sidebarPending){S.sidebarPending=false;scheduleSidebar();}};
  r.ondragover=e=>{const source=S.chatById.get(ChatControls.draggedId());if(canReorder(source,c,n)){e.preventDefault();r.classList.add('drop-target');}};r.ondragleave=()=>r.classList.remove('drop-target');r.ondrop=safeRun(async e=>{e.preventDefault();e.stopPropagation();r.classList.remove('drop-target');const source=S.chatById.get(e.dataTransfer.getData('text/plain'));if(!canReorder(source,c,n)||source.id===c.id)return;const rows=n.rows.filter(x=>x.id!==source.id);rows.splice(rows.indexOf(c),0,source);const changes=rows.map((x,i)=>({id:x.id,position:i*10}));for(const change of changes){Object.assign(S.chatById.get(change.id),change);localOrganization.set(change.id,{...(localOrganization.get(change.id)||{}),...change});}S.sidebarDragging=false;ChatControls.dragging(false);S.settings.groupSort={...S.settings.groupSort,['overview|'+n.key]:'manual'};renderSidebar();await api('/api/organize-many',{changes});await saveSetting('groupSort',S.settings.groupSort);});return r;
 }
 function nodes(tree){const result=[],c=tree.config,searching=!!$('catalog-query').value.trim();document.body.classList.toggle('sidebar-compact',!!c.compact);document.body.classList.toggle('sidebar-overview',true);
  function visit(n,depth,siblings,parent){if(searching&&!n.count)return;const isClosed=!searching&&closed(n,c),head=el('div','group-heading layout-heading'+(n.section?' layout-section':' layout-folder'));head.dataset.group=n.key;head.style.setProperty('--level',depth);const toggle=el('button','group-name');toggle.setAttribute('aria-expanded',String(!isClosed));toggle.append(icon(isClosed?'right':'down'),icon(n.folder?'folder':n.rule==='pins'?'star':n.rule==='bookmarks'?'bookmark':n.rule==='projects'||n.rule==='categories'||n.rule==='folders'?'folder':'chat'),el('span','',n.label));toggle.title=n.source||n.label;toggle.onclick=safeRun(()=>{const next=cfg();next.closed=next.closed.filter(k=>k!==n.key);next.opened=next.opened.filter(k=>k!==n.key);(isClosed?next.opened:next.closed).push(n.key);return saveView(next);});head.append(toggle);if(c.counts)head.append(el('span','count',n.count));
   if(n.count){head.append(control('Sort within '+n.label,'sort',()=>{S.managingGroup='overview|'+n.key;$('group-order-title').textContent='Sort '+n.label;$('group-sort-choice').value=S.settings.groupSort?.[S.managingGroup]||'';modal('group-order-dialog');}));}
   if(n.category!==null&&n.category!==undefined)head.append(control('Rename or remove '+n.label,'more',()=>manageCategory(n.category)));
   if(n.folder){head.draggable=true;head.title=n.source||'Drag to reorder folders';head.ondragstart=e=>{dragFolder={key:n.key,parent};S.sidebarDragging=true;e.dataTransfer.setData('application/x-viewer-layout-folder',n.key);};head.ondragend=()=>{dragFolder=null;S.sidebarDragging=false;if(S.sidebarPending){S.sidebarPending=false;scheduleSidebar();}};}
   head.ondragover=e=>{const source=S.chatById.get(ChatControls.draggedId());if(dragFolder?.parent===parent||source&&assignment(n,source)){e.preventDefault();head.classList.add('drop-target');}};head.ondragleave=()=>head.classList.remove('drop-target');head.ondrop=safeRun(async e=>{head.classList.remove('drop-target');if(dragFolder?.parent===parent){e.preventDefault();const key=e.dataTransfer.getData('application/x-viewer-layout-folder');if(!key||key===n.key)return;const order=siblings.map(x=>x.key).filter(x=>x!==key);order.splice(order.indexOf(n.key),0,key);await saveSetting('groupOrder',{...S.settings.groupOrder,['overview|'+parent]:order});S.sidebarDragging=false;renderSidebar();return;}const source=S.chatById.get(e.dataTransfer.getData('text/plain')),values=source&&assignment(n,source);if(values){e.preventDefault();await organize(source.id,values);S.sidebarDragging=false;ChatControls.dragging(false);renderSidebar();}});
   result.push(head);if(isClosed)return;
   for(const child of n.children)visit(child,depth+1,n.children,n.key);
   const expanded=searching||c.expanded.includes(n.key)||!c.limit,limit=expanded?n.rows.length:c.limit;for(const chat of n.rows.slice(0,limit))result.push(row(chat,n,depth+1));
   if(n.rows.length>c.limit&&c.limit){const more=el('button','layout-show-more',expanded?'Show less':'Show '+(n.rows.length-limit)+' more');more.style.setProperty('--level',depth+1);more.onclick=safeRun(()=>{const next=cfg();next.expanded=expanded?next.expanded.filter(k=>k!==n.key):[...next.expanded,n.key];return saveView(next);});result.push(more);}
   if(!n.count)result.push(el('div','layout-empty',n.rule==='projects'?'No project chats in this view.':'No chats here yet.'));
  }
  for(const n of tree.nodes)visit(n,0,tree.nodes,'root');return result;
 }
 function render(){const tree=SidebarModel.tree(CatalogControls.filter(S.chats),S.settings,S.type,$('show-projects').checked,kind,displayTitle,$('sort').value);CatalogControls.stats(tree.rows);SidebarOrder.reconcile($('chat-list'),nodes(tree));S.sidebarRendering=false;for(const id of sidebarRows.keys())if(!S.chatById.has(id))sidebarRows.delete(id);ChatControls.update();const counts={chat:0,work:0,codex:0};for(const c of S.chats)if(!c.trashed)counts[kind(c)]++;for(const b of document.querySelectorAll('[data-type]'))b.textContent=b.dataset.type==='all'?'All':SidebarModel.labels[b.dataset.type]+' ('+counts[b.dataset.type]+')';if(!tree.rows.length)$('chat-list').append(el('p','empty-list','No chats match this view. Clear filters or choose All.'));$('archive-count').textContent=S.chats.length.toLocaleString()+' available chats';}
 function ruleList(){const box=$('layout-rules');box.replaceChildren();draft.rules.forEach((rule,index)=>{const r=el('div','layout-rule');r.dataset.rule=rule.id;r.style.setProperty('--level',rule.depth);r.draggable=true;const handle=el('span','layout-grip','⠿'),label=el('label'),check=el('input');check.type='checkbox';check.checked=rule.enabled;check.onchange=()=>{rule.enabled=check.checked;};label.append(check,document.createTextNode(SidebarModel.labels[rule.id]));r.append(handle,label);for(const [step,text] of [[-1,'Move up'],[1,'Move down']]){const b=control(text+' '+SidebarModel.labels[rule.id],step<0?'up':'down',()=>{const to=index+step;if(to<0||to>=draft.rules.length)return;[draft.rules[index],draft.rules[to]]=[draft.rules[to],draft.rules[index]];draft=SidebarModel.config(draft);ruleList();});b.disabled=index+step<0||index+step>=draft.rules.length;r.append(b);}const level=el('select');level.setAttribute('aria-label','Nesting for '+SidebarModel.labels[rule.id]);const max=index?Math.min(3,draft.rules[index-1].depth+1):0;for(let depth=0;depth<=max;depth++){const opt=el('option','',depth?'Inside previous · level '+depth:'Top level');opt.value=depth;level.append(opt);}level.value=rule.depth;level.onchange=()=>{rule.depth=Number(level.value);draft=SidebarModel.config(draft);ruleList();};r.append(level);r.ondragstart=e=>{dragRule=rule.id;e.dataTransfer.setData('application/x-viewer-rule',rule.id);};r.ondragend=()=>{dragRule=null;};r.ondragover=e=>{if(dragRule)e.preventDefault();};r.ondrop=e=>{e.preventDefault();if(!dragRule||dragRule===rule.id)return;const from=draft.rules.findIndex(x=>x.id===dragRule),item=draft.rules.splice(from,1)[0];draft.rules.splice(draft.rules.findIndex(x=>x.id===rule.id),0,item);draft=SidebarModel.config(draft);ruleList();};box.append(r);});}
 function open(){draft=cfg();ruleList();for(const key of ['limit','compact','counts','empty','pinsFirst','collapsedFolders']){const input=$('layout-'+key);if(input.type==='checkbox')input.checked=!!draft[key];else input.value=draft[key];}$('layout-dates').checked=S.settings.sidebarDates!==false;modal('layout-dialog');}
 function bind(){const b=$('organization-open');ViewerIcons.set(b,'sliders');b.onclick=open;$('layout-reset').onclick=()=>{draft=SidebarModel.defaults();ruleList();for(const key of ['limit','compact','counts','empty','pinsFirst','collapsedFolders']){const input=$('layout-'+key);if(input.type==='checkbox')input.checked=!!draft[key];else input.value=draft[key];}};$('layout-form').onsubmit=safeRun(async e=>{e.preventDefault();for(const key of ['limit','compact','counts','empty','pinsFirst','collapsedFolders']){const input=$('layout-'+key);draft[key]=input.type==='checkbox'?input.checked:Number(input.value);}const settings={sidebarLayout:SidebarModel.config(draft),group:'overview',sidebarDates:$('layout-dates').checked};Object.assign(S.settings,settings);$('group').value='overview';CatalogControls.sync();renderSidebar();$('layout-dialog').close();await api('/api/settings',settings);});}
 return {render,bind,open,canReorder};
})();
