'use strict';
window.ThreadImages=(()=>{
 const cache=new Map(),pending=new Set(),decoded=new Map();let dialog,stage,picture,caption,counter,previous,next,jump,retry,zoomLabel,active=null,scale=1,x=0,y=0,drag=null,opener=null,serial=0;
 const element=(tag,cls='',text='')=>{const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;};
 const params=(cid,leaf)=>({id:cid,...(leaf?{leaf}:{})});
 const url=(cid,leaf,id)=>'/api/thread-images/content?'+new URLSearchParams({...params(cid,leaf),image:id});
 function catalog(cid,leaf,refresh=false){const key=[cid,leaf||'',S.chatById.get(cid)?.fingerprint||''].join('|');if(refresh&&!pending.has(key))cache.delete(key);if(!cache.has(key)){pending.add(key);const promise=api('/api/thread-images?'+new URLSearchParams(params(cid,leaf))).catch(error=>{cache.delete(key);throw error;}).finally(()=>pending.delete(key));cache.set(key,promise);while(cache.size>8)cache.delete(cache.keys().next().value);}return cache.get(key);}
 function transform(){const maxX=Math.max(0,(picture.offsetWidth*scale-stage.clientWidth)/2),maxY=Math.max(0,(picture.offsetHeight*scale-stage.clientHeight)/2);x=Math.max(-maxX,Math.min(maxX,x));y=Math.max(-maxY,Math.min(maxY,y));picture.style.transform=`translate(${x}px,${y}px) scale(${scale})`;stage.classList.toggle('zoomed',scale>1);zoomLabel.textContent=Math.round(scale*100)+'%';}
 function zoom(value){scale=Math.max(1,Math.min(8,value));if(scale===1)x=y=0;transform();}
 function imageNode(source){if(decoded.has(source)){const img=decoded.get(source);decoded.delete(source);decoded.set(source,img);return img;}const img=element('img','image-picture');img.draggable=false;img.decoding='async';img.onload=()=>{if(picture!==img)return;stage.classList.add('loaded');stage.classList.remove('failed');retry.hidden=true;transform();};img.onerror=()=>{if(picture!==img)return;stage.classList.add('failed');retry.hidden=false;};img.src=source;decoded.set(source,img);while(decoded.size>3){const key=decoded.keys().next().value;const old=decoded.get(key);decoded.delete(key);if(old!==picture)old.removeAttribute('src');}return img;}
 function show(index){if(!active)return;active.index=Math.max(0,Math.min(active.images.length-1,index));const item=active.images[active.index];scale=1;x=y=0;stage.classList.remove('failed','loaded');const img=imageNode(url(active.cid,active.leaf,item.id));picture.replaceWith(img);picture=img;picture.alt=item.name;if(picture.complete){stage.classList.toggle('loaded',picture.naturalWidth>0);stage.classList.toggle('failed',!picture.naturalWidth);}caption.textContent=item.name+' · '+(item.seq===null?'Linked Library image': 'Prompt '+(item.seq+1));counter.textContent=(active.index+1)+' / '+active.images.length;previous.disabled=active.index===0;next.disabled=active.index===active.images.length-1;jump.disabled=item.seq===null;retry.hidden=!(picture.complete&&!picture.naturalWidth);transform();const adjacent=active.images[active.index+1];if(adjacent)imageNode(url(active.cid,active.leaf,adjacent.id));}
 function move(delta){if(active&&active.index+delta>=0&&active.index+delta<active.images.length)show(active.index+delta);}
 function init(){if(dialog)return;dialog=element('dialog','image-dialog');dialog.setAttribute('aria-label','Conversation image viewer');const bar=element('header','image-toolbar'),close=element('button','','×'),minus=element('button','','−'),plus=element('button','','+'),fit=element('button','','Fit');counter=element('span','image-counter');zoomLabel=element('span','image-zoom');jump=element('button','','Go to prompt');close.title='Close image viewer (Escape)';close.setAttribute('aria-label','Close image viewer');minus.title='Zoom out';plus.title='Zoom in';fit.title='Fit image';close.onclick=()=>dialog.close();minus.onclick=()=>zoom(scale/1.3);plus.onclick=()=>zoom(scale*1.3);fit.onclick=()=>zoom(1);bar.append(counter,minus,zoomLabel,plus,fit,jump,close);
  stage=element('div','image-stage');picture=element('img','image-picture');picture.draggable=false;picture.decoding='async';picture.onload=()=>{stage.classList.add('loaded');stage.classList.remove('failed');retry.hidden=true;transform();};picture.onerror=()=>{stage.classList.add('failed');retry.hidden=false;};retry=element('button','image-retry','Image unavailable · Retry');retry.hidden=true;retry.onclick=()=>{if(!active)return;cache.clear();picture.src=url(active.cid,active.leaf,active.images[active.index].id)+'&retry='+Date.now();};stage.append(picture,retry);
  previous=element('button','image-previous','‹');next=element('button','image-next','›');previous.setAttribute('aria-label','Previous image');next.setAttribute('aria-label','Next image');previous.onclick=()=>move(-1);next.onclick=()=>move(1);stage.append(previous,next);caption=element('footer','image-caption');dialog.append(bar,stage,caption);document.body.append(dialog);
  dialog.addEventListener('close',()=>{serial++;active=null;for(const img of decoded.values())img.removeAttribute('src');decoded.clear();picture.removeAttribute('src');opener?.isConnected&&opener.focus({preventScroll:true});drag=null;});jump.onclick=async()=>{const a=active,item=a?.images[a.index];if(item?.seq==null)return;dialog.close();await openChat(a.cid,item.seq,false,a.leaf);};
  dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}else if(e.key==='ArrowRight'){e.preventDefault();move(1);}else if(e.key==='+'||e.key==='='){e.preventDefault();zoom(scale*1.3);}else if(e.key==='-'){e.preventDefault();zoom(scale/1.3);}else if(e.key==='0')zoom(1);});
  stage.addEventListener('wheel',e=>{e.preventDefault();zoom(scale*Math.exp(-e.deltaY*.002));},{passive:false});
  stage.addEventListener('pointerdown',e=>{if(e.target!==picture&&e.target!==stage||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,panX:x,panY:y,zoom:scale};stage.setPointerCapture(e.pointerId);stage.classList.add('dragging');});
  stage.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;if(drag.zoom>1){x=drag.panX+e.clientX-drag.x;y=drag.panY+e.clientY-drag.y;transform();}});
  const end=e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(e.type!=='pointercancel'&&drag.zoom===1&&Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.4)move(dx<0?1:-1);drag=null;stage.classList.remove('dragging');};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);window.addEventListener('resize',()=>active&&transform());
 }
 async function open(cid,id=null,button=null,leaf=null){init();const request=++serial;opener=button;let data=await catalog(cid,leaf,true);if(id&&!data.images.some(i=>i.id===id||i.file_key===id||i.references.includes(id)))data=await catalog(cid,leaf,true);if(request!==serial)return;if(!data.images.length){toast('No saved images are linked to this chat yet.');return;}active={cid,leaf,images:data.images,index:0};show(id===null?0:Math.max(0,data.images.findIndex(i=>i.id===id||i.file_key===id||i.references.includes(id))));if(!dialog.open)dialog.showModal();}
 function close(){serial++;if(dialog?.open)dialog.close();}
 async function populate(host,m,cid,leaf){try{const data=await catalog(cid,leaf);if(!host.isConnected||S.selected?.id!==cid||S.leaf!==leaf)return;host.classList.remove('pending-images');host.replaceChildren();const items=data.images.filter(i=>i.sequences.includes(m.seq)||i.seq===null&&m.seq===data.last_seq);if(items.some(i=>i.seq===null))host.append(element('small','linked-images-label','Other images linked to this chat · prompt not recorded'));for(const item of items){const button=element('button','image-thumbnail');button.title=item.name+' · Open image';button.setAttribute('aria-label','Open image: '+item.name);const img=element('img');img.alt=item.name;img.loading='lazy';img.decoding='async';img.src=url(cid,leaf,item.id);img.onerror=()=>{button.classList.add('unavailable');img.alt='Not saved locally: '+item.name;};button.append(img);button.onclick=()=>open(cid,item.id,button,leaf).catch(e=>toast(e.message));host.append(button);}host.hidden=!items.length;cleanReferences(host.parentElement,items);}catch(error){if(!host.isConnected||S.selected?.id!==cid||S.leaf!==leaf)return;host.hidden=false;host.classList.remove('pending-images');const button=element('button','format-status','Retry loading images'),status=element('small','image-load-error',error.message);status.setAttribute('role','status');button.title=error.message;button.onclick=()=>{button.disabled=true;populate(host,m,cid,leaf);};host.replaceChildren(button,status);}}
 const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){observer.unobserve(e.target);populate(e.target,...e.target._images);}}, {root:document.getElementById('scroller'),rootMargin:'500px'});
 function mount(article,m,cid,leaf){const host=element('div','message-images pending-images');host._images=[m,cid,leaf];article.querySelector('.message-body').prepend(host);observer.observe(host);}
 function cleanReferences(root,items){const refs=items.filter(i=>i.available).flatMap(i=>[...i.references,i.name]),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),texts=[];while(walker.nextNode())texts.push(walker.currentNode);for(const text of texts){if(text.parentElement.closest('pre,code,button,summary'))continue;let value=text.textContent;for(const ref of refs)value=value.split('[Media reference: '+ref+']').join('').split('Attachment reference: '+ref).join('');value=value.replace(/!\[([^\]\n]*)\]\(\s*(<[^>\n]+>|[^\s)]+)(?:\s+["'][^\n]*?["'])?\s*\)/g,(raw,alt,ref)=>refs.includes(ref.replace(/^<|>$/g,''))?'':raw);if(value!==text.textContent)text.textContent=value.replace(/(?:\n[ \t]*){3,}/g,'\n\n');}}
 function bindRendered(root,m,cid,leaf){catalog(cid,leaf).then(data=>{if(root.isConnected)cleanReferences(root,data.images.filter(i=>i.sequences.includes(m.seq)));}).catch(()=>{});for(const img of root.querySelectorAll('img')){if(img.closest('.saved-widget,.source-icon'))continue;img.classList.add('chat-image');img.tabIndex=0;img.setAttribute('role','button');img.title='Open image · Scroll to zoom';const reference=new URL(img.src,location.href).searchParams.get('path');const openImage=()=>open(cid,reference,img,leaf).catch(e=>toast(e.message));img.onclick=openImage;img.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openImage();}};}}
 function release(nodes){for(const n of nodes)for(const host of n.querySelectorAll('.message-images'))observer.unobserve(host);}
 function resume(nodes){for(const n of nodes)for(const host of n.querySelectorAll('.message-images'))observer.observe(host);}
 document.addEventListener('DOMContentLoaded',()=>{const home=document.getElementById('chat-files-open');if(home){const button=element('button','','▧');button.id='chat-images-open';button.title='View all images in this chat';button.setAttribute('aria-label','View all images in this chat');button.onclick=()=>S.selected&&open(S.selected.id,null,button,S.leaf).catch(e=>toast(e.message));home.after(button);}});
 return {catalog,open,close,mount,bindRendered,release,resume};
})();
